package domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProductExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table lgk_product
     *
     * @abatorgenerated Tue Jul 07 10:52:53 CDT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table lgk_product
     *
     * @abatorgenerated Tue Jul 07 10:52:53 CDT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product
     *
     * @abatorgenerated Tue Jul 07 10:52:53 CDT 2020
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product
     *
     * @abatorgenerated Tue Jul 07 10:52:53 CDT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product
     *
     * @abatorgenerated Tue Jul 07 10:52:53 CDT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product
     *
     * @abatorgenerated Tue Jul 07 10:52:53 CDT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product
     *
     * @abatorgenerated Tue Jul 07 10:52:53 CDT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product
     *
     * @abatorgenerated Tue Jul 07 10:52:53 CDT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product
     *
     * @abatorgenerated Tue Jul 07 10:52:53 CDT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product
     *
     * @abatorgenerated Tue Jul 07 10:52:53 CDT 2020
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table lgk_product
     *
     * @abatorgenerated Tue Jul 07 10:52:53 CDT 2020
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andId_productIsNull() {
            addCriterion("id_product is null");
            return this;
        }

        public Criteria andId_productIsNotNull() {
            addCriterion("id_product is not null");
            return this;
        }

        public Criteria andId_productEqualTo(Long value) {
            addCriterion("id_product =", value, "id_product");
            return this;
        }

        public Criteria andId_productNotEqualTo(Long value) {
            addCriterion("id_product <>", value, "id_product");
            return this;
        }

        public Criteria andId_productGreaterThan(Long value) {
            addCriterion("id_product >", value, "id_product");
            return this;
        }

        public Criteria andId_productGreaterThanOrEqualTo(Long value) {
            addCriterion("id_product >=", value, "id_product");
            return this;
        }

        public Criteria andId_productLessThan(Long value) {
            addCriterion("id_product <", value, "id_product");
            return this;
        }

        public Criteria andId_productLessThanOrEqualTo(Long value) {
            addCriterion("id_product <=", value, "id_product");
            return this;
        }

        public Criteria andId_productIn(List<Long> values) {
            addCriterion("id_product in", values, "id_product");
            return this;
        }

        public Criteria andId_productNotIn(List<Long> values) {
            addCriterion("id_product not in", values, "id_product");
            return this;
        }

        public Criteria andId_productBetween(Long value1, Long value2) {
            addCriterion("id_product between", value1, value2, "id_product");
            return this;
        }

        public Criteria andId_productNotBetween(Long value1, Long value2) {
            addCriterion("id_product not between", value1, value2, "id_product");
            return this;
        }

        public Criteria andId_category_productIsNull() {
            addCriterion("id_category_product is null");
            return this;
        }

        public Criteria andId_category_productIsNotNull() {
            addCriterion("id_category_product is not null");
            return this;
        }

        public Criteria andId_category_productEqualTo(Long value) {
            addCriterion("id_category_product =", value, "id_category_product");
            return this;
        }

        public Criteria andId_category_productNotEqualTo(Long value) {
            addCriterion("id_category_product <>", value, "id_category_product");
            return this;
        }

        public Criteria andId_category_productGreaterThan(Long value) {
            addCriterion("id_category_product >", value, "id_category_product");
            return this;
        }

        public Criteria andId_category_productGreaterThanOrEqualTo(Long value) {
            addCriterion("id_category_product >=", value, "id_category_product");
            return this;
        }

        public Criteria andId_category_productLessThan(Long value) {
            addCriterion("id_category_product <", value, "id_category_product");
            return this;
        }

        public Criteria andId_category_productLessThanOrEqualTo(Long value) {
            addCriterion("id_category_product <=", value, "id_category_product");
            return this;
        }

        public Criteria andId_category_productIn(List<Long> values) {
            addCriterion("id_category_product in", values, "id_category_product");
            return this;
        }

        public Criteria andId_category_productNotIn(List<Long> values) {
            addCriterion("id_category_product not in", values, "id_category_product");
            return this;
        }

        public Criteria andId_category_productBetween(Long value1, Long value2) {
            addCriterion("id_category_product between", value1, value2, "id_category_product");
            return this;
        }

        public Criteria andId_category_productNotBetween(Long value1, Long value2) {
            addCriterion("id_category_product not between", value1, value2, "id_category_product");
            return this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("created =", value, "created");
            return this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("created <>", value, "created");
            return this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("created >", value, "created");
            return this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("created >=", value, "created");
            return this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("created <", value, "created");
            return this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("created <=", value, "created");
            return this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("created in", values, "created");
            return this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("created not in", values, "created");
            return this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("created between", value1, value2, "created");
            return this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("created not between", value1, value2, "created");
            return this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("modified is null");
            return this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("modified is not null");
            return this;
        }

        public Criteria andModifiedEqualTo(Date value) {
            addCriterion("modified =", value, "modified");
            return this;
        }

        public Criteria andModifiedNotEqualTo(Date value) {
            addCriterion("modified <>", value, "modified");
            return this;
        }

        public Criteria andModifiedGreaterThan(Date value) {
            addCriterion("modified >", value, "modified");
            return this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("modified >=", value, "modified");
            return this;
        }

        public Criteria andModifiedLessThan(Date value) {
            addCriterion("modified <", value, "modified");
            return this;
        }

        public Criteria andModifiedLessThanOrEqualTo(Date value) {
            addCriterion("modified <=", value, "modified");
            return this;
        }

        public Criteria andModifiedIn(List<Date> values) {
            addCriterion("modified in", values, "modified");
            return this;
        }

        public Criteria andModifiedNotIn(List<Date> values) {
            addCriterion("modified not in", values, "modified");
            return this;
        }

        public Criteria andModifiedBetween(Date value1, Date value2) {
            addCriterion("modified between", value1, value2, "modified");
            return this;
        }

        public Criteria andModifiedNotBetween(Date value1, Date value2) {
            addCriterion("modified not between", value1, value2, "modified");
            return this;
        }

        public Criteria andLoginIsNull() {
            addCriterion("login is null");
            return this;
        }

        public Criteria andLoginIsNotNull() {
            addCriterion("login is not null");
            return this;
        }

        public Criteria andLoginEqualTo(String value) {
            addCriterion("login =", value, "login");
            return this;
        }

        public Criteria andLoginNotEqualTo(String value) {
            addCriterion("login <>", value, "login");
            return this;
        }

        public Criteria andLoginGreaterThan(String value) {
            addCriterion("login >", value, "login");
            return this;
        }

        public Criteria andLoginGreaterThanOrEqualTo(String value) {
            addCriterion("login >=", value, "login");
            return this;
        }

        public Criteria andLoginLessThan(String value) {
            addCriterion("login <", value, "login");
            return this;
        }

        public Criteria andLoginLessThanOrEqualTo(String value) {
            addCriterion("login <=", value, "login");
            return this;
        }

        public Criteria andLoginLike(String value) {
            addCriterion("login like", value, "login");
            return this;
        }

        public Criteria andLoginNotLike(String value) {
            addCriterion("login not like", value, "login");
            return this;
        }

        public Criteria andLoginIn(List<String> values) {
            addCriterion("login in", values, "login");
            return this;
        }

        public Criteria andLoginNotIn(List<String> values) {
            addCriterion("login not in", values, "login");
            return this;
        }

        public Criteria andLoginBetween(String value1, String value2) {
            addCriterion("login between", value1, value2, "login");
            return this;
        }

        public Criteria andLoginNotBetween(String value1, String value2) {
            addCriterion("login not between", value1, value2, "login");
            return this;
        }

        public Criteria andOrderbyIsNull() {
            addCriterion("orderby is null");
            return this;
        }

        public Criteria andOrderbyIsNotNull() {
            addCriterion("orderby is not null");
            return this;
        }

        public Criteria andOrderbyEqualTo(Integer value) {
            addCriterion("orderby =", value, "orderby");
            return this;
        }

        public Criteria andOrderbyNotEqualTo(Integer value) {
            addCriterion("orderby <>", value, "orderby");
            return this;
        }

        public Criteria andOrderbyGreaterThan(Integer value) {
            addCriterion("orderby >", value, "orderby");
            return this;
        }

        public Criteria andOrderbyGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderby >=", value, "orderby");
            return this;
        }

        public Criteria andOrderbyLessThan(Integer value) {
            addCriterion("orderby <", value, "orderby");
            return this;
        }

        public Criteria andOrderbyLessThanOrEqualTo(Integer value) {
            addCriterion("orderby <=", value, "orderby");
            return this;
        }

        public Criteria andOrderbyIn(List<Integer> values) {
            addCriterion("orderby in", values, "orderby");
            return this;
        }

        public Criteria andOrderbyNotIn(List<Integer> values) {
            addCriterion("orderby not in", values, "orderby");
            return this;
        }

        public Criteria andOrderbyBetween(Integer value1, Integer value2) {
            addCriterion("orderby between", value1, value2, "orderby");
            return this;
        }

        public Criteria andOrderbyNotBetween(Integer value1, Integer value2) {
            addCriterion("orderby not between", value1, value2, "orderby");
            return this;
        }

        public Criteria andActiveIsNull() {
            addCriterion("active is null");
            return this;
        }

        public Criteria andActiveIsNotNull() {
            addCriterion("active is not null");
            return this;
        }

        public Criteria andActiveEqualTo(String value) {
            addCriterion("active =", value, "active");
            return this;
        }

        public Criteria andActiveNotEqualTo(String value) {
            addCriterion("active <>", value, "active");
            return this;
        }

        public Criteria andActiveGreaterThan(String value) {
            addCriterion("active >", value, "active");
            return this;
        }

        public Criteria andActiveGreaterThanOrEqualTo(String value) {
            addCriterion("active >=", value, "active");
            return this;
        }

        public Criteria andActiveLessThan(String value) {
            addCriterion("active <", value, "active");
            return this;
        }

        public Criteria andActiveLessThanOrEqualTo(String value) {
            addCriterion("active <=", value, "active");
            return this;
        }

        public Criteria andActiveLike(String value) {
            addCriterion("active like", value, "active");
            return this;
        }

        public Criteria andActiveNotLike(String value) {
            addCriterion("active not like", value, "active");
            return this;
        }

        public Criteria andActiveIn(List<String> values) {
            addCriterion("active in", values, "active");
            return this;
        }

        public Criteria andActiveNotIn(List<String> values) {
            addCriterion("active not in", values, "active");
            return this;
        }

        public Criteria andActiveBetween(String value1, String value2) {
            addCriterion("active between", value1, value2, "active");
            return this;
        }

        public Criteria andActiveNotBetween(String value1, String value2) {
            addCriterion("active not between", value1, value2, "active");
            return this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return this;
        }

        public Criteria andName_shortIsNull() {
            addCriterion("name_short is null");
            return this;
        }

        public Criteria andName_shortIsNotNull() {
            addCriterion("name_short is not null");
            return this;
        }

        public Criteria andName_shortEqualTo(String value) {
            addCriterion("name_short =", value, "name_short");
            return this;
        }

        public Criteria andName_shortNotEqualTo(String value) {
            addCriterion("name_short <>", value, "name_short");
            return this;
        }

        public Criteria andName_shortGreaterThan(String value) {
            addCriterion("name_short >", value, "name_short");
            return this;
        }

        public Criteria andName_shortGreaterThanOrEqualTo(String value) {
            addCriterion("name_short >=", value, "name_short");
            return this;
        }

        public Criteria andName_shortLessThan(String value) {
            addCriterion("name_short <", value, "name_short");
            return this;
        }

        public Criteria andName_shortLessThanOrEqualTo(String value) {
            addCriterion("name_short <=", value, "name_short");
            return this;
        }

        public Criteria andName_shortLike(String value) {
            addCriterion("name_short like", value, "name_short");
            return this;
        }

        public Criteria andName_shortNotLike(String value) {
            addCriterion("name_short not like", value, "name_short");
            return this;
        }

        public Criteria andName_shortIn(List<String> values) {
            addCriterion("name_short in", values, "name_short");
            return this;
        }

        public Criteria andName_shortNotIn(List<String> values) {
            addCriterion("name_short not in", values, "name_short");
            return this;
        }

        public Criteria andName_shortBetween(String value1, String value2) {
            addCriterion("name_short between", value1, value2, "name_short");
            return this;
        }

        public Criteria andName_shortNotBetween(String value1, String value2) {
            addCriterion("name_short not between", value1, value2, "name_short");
            return this;
        }

        public Criteria andName_longIsNull() {
            addCriterion("name_long is null");
            return this;
        }

        public Criteria andName_longIsNotNull() {
            addCriterion("name_long is not null");
            return this;
        }

        public Criteria andName_longEqualTo(String value) {
            addCriterion("name_long =", value, "name_long");
            return this;
        }

        public Criteria andName_longNotEqualTo(String value) {
            addCriterion("name_long <>", value, "name_long");
            return this;
        }

        public Criteria andName_longGreaterThan(String value) {
            addCriterion("name_long >", value, "name_long");
            return this;
        }

        public Criteria andName_longGreaterThanOrEqualTo(String value) {
            addCriterion("name_long >=", value, "name_long");
            return this;
        }

        public Criteria andName_longLessThan(String value) {
            addCriterion("name_long <", value, "name_long");
            return this;
        }

        public Criteria andName_longLessThanOrEqualTo(String value) {
            addCriterion("name_long <=", value, "name_long");
            return this;
        }

        public Criteria andName_longLike(String value) {
            addCriterion("name_long like", value, "name_long");
            return this;
        }

        public Criteria andName_longNotLike(String value) {
            addCriterion("name_long not like", value, "name_long");
            return this;
        }

        public Criteria andName_longIn(List<String> values) {
            addCriterion("name_long in", values, "name_long");
            return this;
        }

        public Criteria andName_longNotIn(List<String> values) {
            addCriterion("name_long not in", values, "name_long");
            return this;
        }

        public Criteria andName_longBetween(String value1, String value2) {
            addCriterion("name_long between", value1, value2, "name_long");
            return this;
        }

        public Criteria andName_longNotBetween(String value1, String value2) {
            addCriterion("name_long not between", value1, value2, "name_long");
            return this;
        }

        public Criteria andPrice_saleIsNull() {
            addCriterion("price_sale is null");
            return this;
        }

        public Criteria andPrice_saleIsNotNull() {
            addCriterion("price_sale is not null");
            return this;
        }

        public Criteria andPrice_saleEqualTo(Double value) {
            addCriterion("price_sale =", value, "price_sale");
            return this;
        }

        public Criteria andPrice_saleNotEqualTo(Double value) {
            addCriterion("price_sale <>", value, "price_sale");
            return this;
        }

        public Criteria andPrice_saleGreaterThan(Double value) {
            addCriterion("price_sale >", value, "price_sale");
            return this;
        }

        public Criteria andPrice_saleGreaterThanOrEqualTo(Double value) {
            addCriterion("price_sale >=", value, "price_sale");
            return this;
        }

        public Criteria andPrice_saleLessThan(Double value) {
            addCriterion("price_sale <", value, "price_sale");
            return this;
        }

        public Criteria andPrice_saleLessThanOrEqualTo(Double value) {
            addCriterion("price_sale <=", value, "price_sale");
            return this;
        }

        public Criteria andPrice_saleIn(List<Double> values) {
            addCriterion("price_sale in", values, "price_sale");
            return this;
        }

        public Criteria andPrice_saleNotIn(List<Double> values) {
            addCriterion("price_sale not in", values, "price_sale");
            return this;
        }

        public Criteria andPrice_saleBetween(Double value1, Double value2) {
            addCriterion("price_sale between", value1, value2, "price_sale");
            return this;
        }

        public Criteria andPrice_saleNotBetween(Double value1, Double value2) {
            addCriterion("price_sale not between", value1, value2, "price_sale");
            return this;
        }

        public Criteria andPrice_costIsNull() {
            addCriterion("price_cost is null");
            return this;
        }

        public Criteria andPrice_costIsNotNull() {
            addCriterion("price_cost is not null");
            return this;
        }

        public Criteria andPrice_costEqualTo(Double value) {
            addCriterion("price_cost =", value, "price_cost");
            return this;
        }

        public Criteria andPrice_costNotEqualTo(Double value) {
            addCriterion("price_cost <>", value, "price_cost");
            return this;
        }

        public Criteria andPrice_costGreaterThan(Double value) {
            addCriterion("price_cost >", value, "price_cost");
            return this;
        }

        public Criteria andPrice_costGreaterThanOrEqualTo(Double value) {
            addCriterion("price_cost >=", value, "price_cost");
            return this;
        }

        public Criteria andPrice_costLessThan(Double value) {
            addCriterion("price_cost <", value, "price_cost");
            return this;
        }

        public Criteria andPrice_costLessThanOrEqualTo(Double value) {
            addCriterion("price_cost <=", value, "price_cost");
            return this;
        }

        public Criteria andPrice_costIn(List<Double> values) {
            addCriterion("price_cost in", values, "price_cost");
            return this;
        }

        public Criteria andPrice_costNotIn(List<Double> values) {
            addCriterion("price_cost not in", values, "price_cost");
            return this;
        }

        public Criteria andPrice_costBetween(Double value1, Double value2) {
            addCriterion("price_cost between", value1, value2, "price_cost");
            return this;
        }

        public Criteria andPrice_costNotBetween(Double value1, Double value2) {
            addCriterion("price_cost not between", value1, value2, "price_cost");
            return this;
        }

        public Criteria andImageIsNull() {
            addCriterion("image is null");
            return this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("image is not null");
            return this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("image like", value, "image");
            return this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return this;
        }

        public Criteria andImageIn(List<String> values) {
            addCriterion("image in", values, "image");
            return this;
        }

        public Criteria andImageNotIn(List<String> values) {
            addCriterion("image not in", values, "image");
            return this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return this;
        }

        public Criteria andId_brandIsNull() {
            addCriterion("id_brand is null");
            return this;
        }

        public Criteria andId_brandIsNotNull() {
            addCriterion("id_brand is not null");
            return this;
        }

        public Criteria andId_brandEqualTo(Long value) {
            addCriterion("id_brand =", value, "id_brand");
            return this;
        }

        public Criteria andId_brandNotEqualTo(Long value) {
            addCriterion("id_brand <>", value, "id_brand");
            return this;
        }

        public Criteria andId_brandGreaterThan(Long value) {
            addCriterion("id_brand >", value, "id_brand");
            return this;
        }

        public Criteria andId_brandGreaterThanOrEqualTo(Long value) {
            addCriterion("id_brand >=", value, "id_brand");
            return this;
        }

        public Criteria andId_brandLessThan(Long value) {
            addCriterion("id_brand <", value, "id_brand");
            return this;
        }

        public Criteria andId_brandLessThanOrEqualTo(Long value) {
            addCriterion("id_brand <=", value, "id_brand");
            return this;
        }

        public Criteria andId_brandIn(List<Long> values) {
            addCriterion("id_brand in", values, "id_brand");
            return this;
        }

        public Criteria andId_brandNotIn(List<Long> values) {
            addCriterion("id_brand not in", values, "id_brand");
            return this;
        }

        public Criteria andId_brandBetween(Long value1, Long value2) {
            addCriterion("id_brand between", value1, value2, "id_brand");
            return this;
        }

        public Criteria andId_brandNotBetween(Long value1, Long value2) {
            addCriterion("id_brand not between", value1, value2, "id_brand");
            return this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("flag is null");
            return this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("flag is not null");
            return this;
        }

        public Criteria andFlagEqualTo(String value) {
            addCriterion("flag =", value, "flag");
            return this;
        }

        public Criteria andFlagNotEqualTo(String value) {
            addCriterion("flag <>", value, "flag");
            return this;
        }

        public Criteria andFlagGreaterThan(String value) {
            addCriterion("flag >", value, "flag");
            return this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(String value) {
            addCriterion("flag >=", value, "flag");
            return this;
        }

        public Criteria andFlagLessThan(String value) {
            addCriterion("flag <", value, "flag");
            return this;
        }

        public Criteria andFlagLessThanOrEqualTo(String value) {
            addCriterion("flag <=", value, "flag");
            return this;
        }

        public Criteria andFlagLike(String value) {
            addCriterion("flag like", value, "flag");
            return this;
        }

        public Criteria andFlagNotLike(String value) {
            addCriterion("flag not like", value, "flag");
            return this;
        }

        public Criteria andFlagIn(List<String> values) {
            addCriterion("flag in", values, "flag");
            return this;
        }

        public Criteria andFlagNotIn(List<String> values) {
            addCriterion("flag not in", values, "flag");
            return this;
        }

        public Criteria andFlagBetween(String value1, String value2) {
            addCriterion("flag between", value1, value2, "flag");
            return this;
        }

        public Criteria andFlagNotBetween(String value1, String value2) {
            addCriterion("flag not between", value1, value2, "flag");
            return this;
        }

        public Criteria andPrice_cost_boxIsNull() {
            addCriterion("price_cost_box is null");
            return this;
        }

        public Criteria andPrice_cost_boxIsNotNull() {
            addCriterion("price_cost_box is not null");
            return this;
        }

        public Criteria andPrice_cost_boxEqualTo(Double value) {
            addCriterion("price_cost_box =", value, "price_cost_box");
            return this;
        }

        public Criteria andPrice_cost_boxNotEqualTo(Double value) {
            addCriterion("price_cost_box <>", value, "price_cost_box");
            return this;
        }

        public Criteria andPrice_cost_boxGreaterThan(Double value) {
            addCriterion("price_cost_box >", value, "price_cost_box");
            return this;
        }

        public Criteria andPrice_cost_boxGreaterThanOrEqualTo(Double value) {
            addCriterion("price_cost_box >=", value, "price_cost_box");
            return this;
        }

        public Criteria andPrice_cost_boxLessThan(Double value) {
            addCriterion("price_cost_box <", value, "price_cost_box");
            return this;
        }

        public Criteria andPrice_cost_boxLessThanOrEqualTo(Double value) {
            addCriterion("price_cost_box <=", value, "price_cost_box");
            return this;
        }

        public Criteria andPrice_cost_boxIn(List<Double> values) {
            addCriterion("price_cost_box in", values, "price_cost_box");
            return this;
        }

        public Criteria andPrice_cost_boxNotIn(List<Double> values) {
            addCriterion("price_cost_box not in", values, "price_cost_box");
            return this;
        }

        public Criteria andPrice_cost_boxBetween(Double value1, Double value2) {
            addCriterion("price_cost_box between", value1, value2, "price_cost_box");
            return this;
        }

        public Criteria andPrice_cost_boxNotBetween(Double value1, Double value2) {
            addCriterion("price_cost_box not between", value1, value2, "price_cost_box");
            return this;
        }

        public Criteria andPiece_in_boxIsNull() {
            addCriterion("piece_in_box is null");
            return this;
        }

        public Criteria andPiece_in_boxIsNotNull() {
            addCriterion("piece_in_box is not null");
            return this;
        }

        public Criteria andPiece_in_boxEqualTo(Long value) {
            addCriterion("piece_in_box =", value, "piece_in_box");
            return this;
        }

        public Criteria andPiece_in_boxNotEqualTo(Long value) {
            addCriterion("piece_in_box <>", value, "piece_in_box");
            return this;
        }

        public Criteria andPiece_in_boxGreaterThan(Long value) {
            addCriterion("piece_in_box >", value, "piece_in_box");
            return this;
        }

        public Criteria andPiece_in_boxGreaterThanOrEqualTo(Long value) {
            addCriterion("piece_in_box >=", value, "piece_in_box");
            return this;
        }

        public Criteria andPiece_in_boxLessThan(Long value) {
            addCriterion("piece_in_box <", value, "piece_in_box");
            return this;
        }

        public Criteria andPiece_in_boxLessThanOrEqualTo(Long value) {
            addCriterion("piece_in_box <=", value, "piece_in_box");
            return this;
        }

        public Criteria andPiece_in_boxIn(List<Long> values) {
            addCriterion("piece_in_box in", values, "piece_in_box");
            return this;
        }

        public Criteria andPiece_in_boxNotIn(List<Long> values) {
            addCriterion("piece_in_box not in", values, "piece_in_box");
            return this;
        }

        public Criteria andPiece_in_boxBetween(Long value1, Long value2) {
            addCriterion("piece_in_box between", value1, value2, "piece_in_box");
            return this;
        }

        public Criteria andPiece_in_boxNotBetween(Long value1, Long value2) {
            addCriterion("piece_in_box not between", value1, value2, "piece_in_box");
            return this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return this;
        }

        public Criteria andPrice_sale_boxIsNull() {
            addCriterion("price_sale_box is null");
            return this;
        }

        public Criteria andPrice_sale_boxIsNotNull() {
            addCriterion("price_sale_box is not null");
            return this;
        }

        public Criteria andPrice_sale_boxEqualTo(Double value) {
            addCriterion("price_sale_box =", value, "price_sale_box");
            return this;
        }

        public Criteria andPrice_sale_boxNotEqualTo(Double value) {
            addCriterion("price_sale_box <>", value, "price_sale_box");
            return this;
        }

        public Criteria andPrice_sale_boxGreaterThan(Double value) {
            addCriterion("price_sale_box >", value, "price_sale_box");
            return this;
        }

        public Criteria andPrice_sale_boxGreaterThanOrEqualTo(Double value) {
            addCriterion("price_sale_box >=", value, "price_sale_box");
            return this;
        }

        public Criteria andPrice_sale_boxLessThan(Double value) {
            addCriterion("price_sale_box <", value, "price_sale_box");
            return this;
        }

        public Criteria andPrice_sale_boxLessThanOrEqualTo(Double value) {
            addCriterion("price_sale_box <=", value, "price_sale_box");
            return this;
        }

        public Criteria andPrice_sale_boxIn(List<Double> values) {
            addCriterion("price_sale_box in", values, "price_sale_box");
            return this;
        }

        public Criteria andPrice_sale_boxNotIn(List<Double> values) {
            addCriterion("price_sale_box not in", values, "price_sale_box");
            return this;
        }

        public Criteria andPrice_sale_boxBetween(Double value1, Double value2) {
            addCriterion("price_sale_box between", value1, value2, "price_sale_box");
            return this;
        }

        public Criteria andPrice_sale_boxNotBetween(Double value1, Double value2) {
            addCriterion("price_sale_box not between", value1, value2, "price_sale_box");
            return this;
        }

        public Criteria andTaxIsNull() {
            addCriterion("tax is null");
            return this;
        }

        public Criteria andTaxIsNotNull() {
            addCriterion("tax is not null");
            return this;
        }

        public Criteria andTaxEqualTo(Integer value) {
            addCriterion("tax =", value, "tax");
            return this;
        }

        public Criteria andTaxNotEqualTo(Integer value) {
            addCriterion("tax <>", value, "tax");
            return this;
        }

        public Criteria andTaxGreaterThan(Integer value) {
            addCriterion("tax >", value, "tax");
            return this;
        }

        public Criteria andTaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("tax >=", value, "tax");
            return this;
        }

        public Criteria andTaxLessThan(Integer value) {
            addCriterion("tax <", value, "tax");
            return this;
        }

        public Criteria andTaxLessThanOrEqualTo(Integer value) {
            addCriterion("tax <=", value, "tax");
            return this;
        }

        public Criteria andTaxIn(List<Integer> values) {
            addCriterion("tax in", values, "tax");
            return this;
        }

        public Criteria andTaxNotIn(List<Integer> values) {
            addCriterion("tax not in", values, "tax");
            return this;
        }

        public Criteria andTaxBetween(Integer value1, Integer value2) {
            addCriterion("tax between", value1, value2, "tax");
            return this;
        }

        public Criteria andTaxNotBetween(Integer value1, Integer value2) {
            addCriterion("tax not between", value1, value2, "tax");
            return this;
        }
    }
}