package com.retailsbs.logistikapp.retail.dao;

import java.util.List;

import com.retailsbs.logistikapp.retail.domain.City;
import com.retailsbs.logistikapp.retail.dto.CityExample;

public interface CityDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    Long insert(City record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    int updateByPrimaryKey(City record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    List<City> selectByExample(CityExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    City selectByPrimaryKey(Long id_city);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    int deleteByPrimaryKey(Long id_city);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    int countByExample(CityExample example);
}