package com.retailsbs.logistikapp.retail.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.retail.dao.ActivesDAO;
import com.retailsbs.logistikapp.retail.domain.Actives;
import com.retailsbs.logistikapp.retail.dto.ActivesExample;

public class ActivesDAOImpl extends SqlMapClientDaoSupport implements ActivesDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives
     *
     * @abatorgenerated Wed Nov 01 13:45:22 CST 2017
     */
    public ActivesDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives
     *
     * @abatorgenerated Wed Nov 01 13:45:22 CST 2017
     */
    public Integer insert(Actives record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_actives.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives
     *
     * @abatorgenerated Wed Nov 01 13:45:22 CST 2017
     */
    public int updateByPrimaryKey(Actives record) {
        int rows = getSqlMapClientTemplate().update("lgk_actives.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives
     *
     * @abatorgenerated Wed Nov 01 13:45:22 CST 2017
     */
    public int updateByPrimaryKeySelective(Actives record) {
        int rows = getSqlMapClientTemplate().update("lgk_actives.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives
     *
     * @abatorgenerated Wed Nov 01 13:45:22 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<Actives> selectByExample(ActivesExample example) {
        List<Actives> list = (List<Actives>) getSqlMapClientTemplate().queryForList("lgk_actives.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives
     *
     * @abatorgenerated Wed Nov 01 13:45:22 CST 2017
     */
    public Actives selectByPrimaryKey(Integer idActives) {
        Actives key = new Actives();
        key.setIdActives(idActives);
        Actives record = (Actives) getSqlMapClientTemplate().queryForObject("lgk_actives.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives
     *
     * @abatorgenerated Wed Nov 01 13:45:22 CST 2017
     */
    public int deleteByPrimaryKey(Integer idActives) {
        Actives key = new Actives();
        key.setIdActives(idActives);
        int rows = getSqlMapClientTemplate().delete("lgk_actives.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives
     *
     * @abatorgenerated Wed Nov 01 13:45:22 CST 2017
     */
    public int countByExample(ActivesExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_actives.abatorgenerated_countByExample", example);
        return count;
    }
}