package com.retailsbs.logistikapp.retail.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.retail.dao.ActivesVisitedDAO;
import com.retailsbs.logistikapp.retail.domain.ActivesVisited;
import com.retailsbs.logistikapp.retail.dto.ActivesVisitedExample;

public class ActivesVisitedDAOImpl extends SqlMapClientDaoSupport implements ActivesVisitedDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives_visited
     *
     * @abatorgenerated Thu Nov 09 15:17:29 CST 2017
     */
    public ActivesVisitedDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives_visited
     *
     * @abatorgenerated Thu Nov 09 15:17:29 CST 2017
     */
    public Integer insert(ActivesVisited record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_actives_visited.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives_visited
     *
     * @abatorgenerated Thu Nov 09 15:17:29 CST 2017
     */
    public int updateByPrimaryKey(ActivesVisited record) {
        int rows = getSqlMapClientTemplate().update("lgk_actives_visited.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives_visited
     *
     * @abatorgenerated Thu Nov 09 15:17:29 CST 2017
     */
    public int updateByPrimaryKeySelective(ActivesVisited record) {
        int rows = getSqlMapClientTemplate().update("lgk_actives_visited.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives_visited
     *
     * @abatorgenerated Thu Nov 09 15:17:29 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<ActivesVisited> selectByExample(ActivesVisitedExample example) {
        List<ActivesVisited> list = (List<ActivesVisited>) getSqlMapClientTemplate().queryForList("lgk_actives_visited.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives_visited
     *
     * @abatorgenerated Thu Nov 09 15:17:29 CST 2017
     */
    public ActivesVisited selectByPrimaryKey(Integer idActivesVisited) {
        ActivesVisited key = new ActivesVisited();
        key.setIdActivesVisited(idActivesVisited);
        ActivesVisited record = (ActivesVisited) getSqlMapClientTemplate().queryForObject("lgk_actives_visited.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives_visited
     *
     * @abatorgenerated Thu Nov 09 15:17:29 CST 2017
     */
    public int deleteByPrimaryKey(Integer idActivesVisited) {
        ActivesVisited key = new ActivesVisited();
        key.setIdActivesVisited(idActivesVisited);
        int rows = getSqlMapClientTemplate().delete("lgk_actives_visited.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_actives_visited
     *
     * @abatorgenerated Thu Nov 09 15:17:29 CST 2017
     */
    public int countByExample(ActivesVisitedExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_actives_visited.abatorgenerated_countByExample", example);
        return count;
    }
}