package com.retailsbs.logistikapp.retail.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.retail.dao.CityDAO;
import com.retailsbs.logistikapp.retail.domain.City;
import com.retailsbs.logistikapp.retail.dto.CityExample;

public class CityDAOImpl extends SqlMapClientDaoSupport implements CityDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public CityDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public Long insert(City record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_city.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int updateByPrimaryKey(City record) {
        int rows = getSqlMapClientTemplate().update("lgk_city.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int updateByPrimaryKeySelective(City record) {
        int rows = getSqlMapClientTemplate().update("lgk_city.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<City> selectByExample(CityExample example) {
        List<City> list = (List<City>) getSqlMapClientTemplate().queryForList("lgk_city.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public City selectByPrimaryKey(Long id_city) {
        City key = new City();
        key.setId_city(id_city);
        City record = (City) getSqlMapClientTemplate().queryForObject("lgk_city.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int deleteByPrimaryKey(Long id_city) {
        City key = new City();
        key.setId_city(id_city);
        int rows = getSqlMapClientTemplate().delete("lgk_city.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_city
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int countByExample(CityExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_city.abatorgenerated_countByExample", example);
        return count;
    }
}