package com.retailsbs.logistikapp.retail.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.retail.dao.LocalityDAO;
import com.retailsbs.logistikapp.retail.domain.Locality;
import com.retailsbs.logistikapp.retail.dto.LocalityExample;

public class LocalityDAOImpl extends SqlMapClientDaoSupport implements LocalityDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_locality
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public LocalityDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_locality
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public Long insert(Locality record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_locality.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_locality
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int updateByPrimaryKey(Locality record) {
        int rows = getSqlMapClientTemplate().update("lgk_locality.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_locality
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int updateByPrimaryKeySelective(Locality record) {
        int rows = getSqlMapClientTemplate().update("lgk_locality.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_locality
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<Locality> selectByExample(LocalityExample example) {
        List<Locality> list = (List<Locality>) getSqlMapClientTemplate().queryForList("lgk_locality.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_locality
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public Locality selectByPrimaryKey(Long id_locality) {
        Locality key = new Locality();
        key.setId_locality(id_locality);
        Locality record = (Locality) getSqlMapClientTemplate().queryForObject("lgk_locality.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_locality
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int deleteByPrimaryKey(Long id_locality) {
        Locality key = new Locality();
        key.setId_locality(id_locality);
        int rows = getSqlMapClientTemplate().delete("lgk_locality.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_locality
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int countByExample(LocalityExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_locality.abatorgenerated_countByExample", example);
        return count;
    }
}