package com.retailsbs.logistikapp.retail.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.retail.dao.RetailDAO;
import com.retailsbs.logistikapp.retail.domain.Retail;
import com.retailsbs.logistikapp.retail.dto.RetailExample;

public class RetailDAOImpl extends SqlMapClientDaoSupport implements RetailDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail
     *
     * @abatorgenerated Wed Mar 02 13:38:53 CST 2016
     */
    public RetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail
     *
     * @abatorgenerated Wed Mar 02 13:38:53 CST 2016
     */
    public Long insert(Retail record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_retail.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail
     *
     * @abatorgenerated Wed Mar 02 13:38:53 CST 2016
     */
    public int updateByPrimaryKey(Retail record) {
        int rows = getSqlMapClientTemplate().update("lgk_retail.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail
     *
     * @abatorgenerated Wed Mar 02 13:38:53 CST 2016
     */
    public int updateByPrimaryKeySelective(Retail record) {
        int rows = getSqlMapClientTemplate().update("lgk_retail.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail
     *
     * @abatorgenerated Wed Mar 02 13:38:53 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<Retail> selectByExample(RetailExample example) {
        List<Retail> list = (List<Retail>) getSqlMapClientTemplate().queryForList("lgk_retail.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail
     *
     * @abatorgenerated Wed Mar 02 13:38:53 CST 2016
     */
    public Retail selectByPrimaryKey(Long id_retail) {
        Retail key = new Retail();
        key.setId_retail(id_retail);
        Retail record = (Retail) getSqlMapClientTemplate().queryForObject("lgk_retail.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail
     *
     * @abatorgenerated Wed Mar 02 13:38:53 CST 2016
     */
    public int deleteByPrimaryKey(Long id_retail) {
        Retail key = new Retail();
        key.setId_retail(id_retail);
        int rows = getSqlMapClientTemplate().delete("lgk_retail.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail
     *
     * @abatorgenerated Wed Mar 02 13:38:53 CST 2016
     */
    public int countByExample(RetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_retail.abatorgenerated_countByExample", example);
        return count;
    }
}