package com.retailsbs.logistikapp.retail.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.retail.dao.RetailCategoryDAO;
import com.retailsbs.logistikapp.retail.domain.RetailCategory;
import com.retailsbs.logistikapp.retail.dto.RetailCategoryExample;

public class RetailCategoryDAOImpl extends SqlMapClientDaoSupport implements RetailCategoryDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail_category
     *
     * @abatorgenerated Thu Jan 15 12:56:46 CST 2015
     */
    public RetailCategoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail_category
     *
     * @abatorgenerated Thu Jan 15 12:56:46 CST 2015
     */
    public Long insert(RetailCategory record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_retail_category.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail_category
     *
     * @abatorgenerated Thu Jan 15 12:56:46 CST 2015
     */
    public int updateByPrimaryKey(RetailCategory record) {
        int rows = getSqlMapClientTemplate().update("lgk_retail_category.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail_category
     *
     * @abatorgenerated Thu Jan 15 12:56:46 CST 2015
     */
    public int updateByPrimaryKeySelective(RetailCategory record) {
        int rows = getSqlMapClientTemplate().update("lgk_retail_category.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail_category
     *
     * @abatorgenerated Thu Jan 15 12:56:46 CST 2015
     */
    @SuppressWarnings("unchecked")
    public List<RetailCategory> selectByExample(RetailCategoryExample example) {
        List<RetailCategory> list = (List<RetailCategory>) getSqlMapClientTemplate().queryForList("lgk_retail_category.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail_category
     *
     * @abatorgenerated Thu Jan 15 12:56:46 CST 2015
     */
    public RetailCategory selectByPrimaryKey(Long id_retail_category) {
        RetailCategory key = new RetailCategory();
        key.setId_retail_category(id_retail_category);
        RetailCategory record = (RetailCategory) getSqlMapClientTemplate().queryForObject("lgk_retail_category.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail_category
     *
     * @abatorgenerated Thu Jan 15 12:56:46 CST 2015
     */
    public int deleteByPrimaryKey(Long id_retail_category) {
        RetailCategory key = new RetailCategory();
        key.setId_retail_category(id_retail_category);
        int rows = getSqlMapClientTemplate().delete("lgk_retail_category.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retail_category
     *
     * @abatorgenerated Thu Jan 15 12:56:46 CST 2015
     */
    public int countByExample(RetailCategoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_retail_category.abatorgenerated_countByExample", example);
        return count;
    }
}