package com.retailsbs.logistikapp.retail.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.retail.dao.StateDAO;
import com.retailsbs.logistikapp.retail.domain.State;
import com.retailsbs.logistikapp.retail.dto.StateExample;

public class StateDAOImpl extends SqlMapClientDaoSupport implements StateDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_state
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public StateDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_state
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public Long insert(State record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_state.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_state
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int updateByPrimaryKey(State record) {
        int rows = getSqlMapClientTemplate().update("lgk_state.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_state
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int updateByPrimaryKeySelective(State record) {
        int rows = getSqlMapClientTemplate().update("lgk_state.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_state
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<State> selectByExample(StateExample example) {
        List<State> list = (List<State>) getSqlMapClientTemplate().queryForList("lgk_state.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_state
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public State selectByPrimaryKey(Long id_state) {
        State key = new State();
        key.setId_state(id_state);
        State record = (State) getSqlMapClientTemplate().queryForObject("lgk_state.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_state
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int deleteByPrimaryKey(Long id_state) {
        State key = new State();
        key.setId_state(id_state);
        int rows = getSqlMapClientTemplate().delete("lgk_state.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_state
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public int countByExample(StateExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_state.abatorgenerated_countByExample", example);
        return count;
    }
}