package com.retailsbs.logistikapp.retail.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.retail.dao.StoreDAO;
import com.retailsbs.logistikapp.retail.domain.Store;
import com.retailsbs.logistikapp.retail.dto.StoreExample;

public class StoreDAOImpl extends SqlMapClientDaoSupport implements StoreDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store
     *
     * @abatorgenerated Mon Mar 28 13:23:45 CST 2016
     */
    public StoreDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store
     *
     * @abatorgenerated Mon Mar 28 13:23:45 CST 2016
     */
    public Long insert(Store record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_store.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store
     *
     * @abatorgenerated Mon Mar 28 13:23:45 CST 2016
     */
    public int updateByPrimaryKey(Store record) {
        int rows = getSqlMapClientTemplate().update("lgk_store.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store
     *
     * @abatorgenerated Mon Mar 28 13:23:45 CST 2016
     */
    public int updateByPrimaryKeySelective(Store record) {
        int rows = getSqlMapClientTemplate().update("lgk_store.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store
     *
     * @abatorgenerated Mon Mar 28 13:23:45 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<Store> selectByExample(StoreExample example) {
        List<Store> list = (List<Store>) getSqlMapClientTemplate().queryForList("lgk_store.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store
     *
     * @abatorgenerated Mon Mar 28 13:23:45 CST 2016
     */
    public Store selectByPrimaryKey(Long id_store) {
        Store key = new Store();
        key.setId_store(id_store);
        Store record = (Store) getSqlMapClientTemplate().queryForObject("lgk_store.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store
     *
     * @abatorgenerated Mon Mar 28 13:23:45 CST 2016
     */
    public int deleteByPrimaryKey(Long id_store) {
        Store key = new Store();
        key.setId_store(id_store);
        int rows = getSqlMapClientTemplate().delete("lgk_store.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store
     *
     * @abatorgenerated Mon Mar 28 13:23:45 CST 2016
     */
    public int countByExample(StoreExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_store.abatorgenerated_countByExample", example);
        return count;
    }
}