package com.retailsbs.logistikapp.retail.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.retail.dao.StoreCategoryDAO;
import com.retailsbs.logistikapp.retail.domain.StoreCategory;
import com.retailsbs.logistikapp.retail.dto.StoreCategoryExample;

public class StoreCategoryDAOImpl extends SqlMapClientDaoSupport implements StoreCategoryDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category
     *
     * @abatorgenerated Tue Feb 03 11:46:19 CST 2015
     */
    public StoreCategoryDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category
     *
     * @abatorgenerated Tue Feb 03 11:46:19 CST 2015
     */
    public Long insert(StoreCategory record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_store_category.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category
     *
     * @abatorgenerated Tue Feb 03 11:46:19 CST 2015
     */
    public int updateByPrimaryKey(StoreCategory record) {
        int rows = getSqlMapClientTemplate().update("lgk_store_category.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category
     *
     * @abatorgenerated Tue Feb 03 11:46:19 CST 2015
     */
    public int updateByPrimaryKeySelective(StoreCategory record) {
        int rows = getSqlMapClientTemplate().update("lgk_store_category.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category
     *
     * @abatorgenerated Tue Feb 03 11:46:19 CST 2015
     */
    @SuppressWarnings("unchecked")
    public List<StoreCategory> selectByExample(StoreCategoryExample example) {
        List<StoreCategory> list = (List<StoreCategory>) getSqlMapClientTemplate().queryForList("lgk_store_category.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category
     *
     * @abatorgenerated Tue Feb 03 11:46:19 CST 2015
     */
    public StoreCategory selectByPrimaryKey(Long id_store_category) {
        StoreCategory key = new StoreCategory();
        key.setId_store_category(id_store_category);
        StoreCategory record = (StoreCategory) getSqlMapClientTemplate().queryForObject("lgk_store_category.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category
     *
     * @abatorgenerated Tue Feb 03 11:46:19 CST 2015
     */
    public int deleteByPrimaryKey(Long id_store_category) {
        StoreCategory key = new StoreCategory();
        key.setId_store_category(id_store_category);
        int rows = getSqlMapClientTemplate().delete("lgk_store_category.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category
     *
     * @abatorgenerated Tue Feb 03 11:46:19 CST 2015
     */
    public int countByExample(StoreCategoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_store_category.abatorgenerated_countByExample", example);
        return count;
    }
}