package com.retailsbs.logistikapp.user.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.user.dao.AttachmentDAO;
import com.retailsbs.logistikapp.user.domain.Attachment;
import com.retailsbs.logistikapp.user.dto.AttachmentExample;

public class AttachmentDAOImpl extends SqlMapClientDaoSupport implements AttachmentDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public AttachmentDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public Long insert(Attachment record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_attachment.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public int updateByPrimaryKey(Attachment record) {
        int rows = getSqlMapClientTemplate().update("lgk_attachment.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public int updateByPrimaryKeySelective(Attachment record) {
        int rows = getSqlMapClientTemplate().update("lgk_attachment.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<Attachment> selectByExample(AttachmentExample example) {
        List<Attachment> list = (List<Attachment>) getSqlMapClientTemplate().queryForList("lgk_attachment.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public Attachment selectByPrimaryKey(Long id_attachment) {
        Attachment key = new Attachment();
        key.setId_attachment(id_attachment);
        Attachment record = (Attachment) getSqlMapClientTemplate().queryForObject("lgk_attachment.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public int deleteByPrimaryKey(Long id_attachment) {
        Attachment key = new Attachment();
        key.setId_attachment(id_attachment);
        int rows = getSqlMapClientTemplate().delete("lgk_attachment.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public int countByExample(AttachmentExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_attachment.abatorgenerated_countByExample", example);
        return count;
    }
}