package com.retailsbs.logistikapp.user.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.user.dao.GroupDAO;
import com.retailsbs.logistikapp.user.domain.Group;
import com.retailsbs.logistikapp.user.dto.GroupExample;

public class GroupDAOImpl extends SqlMapClientDaoSupport implements GroupDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_group
     *
     * @abatorgenerated Mon Aug 03 13:51:36 CDT 2015
     */
    public GroupDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_group
     *
     * @abatorgenerated Mon Aug 03 13:51:36 CDT 2015
     */
    public Long insert(Group record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_group.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_group
     *
     * @abatorgenerated Mon Aug 03 13:51:36 CDT 2015
     */
    public int updateByPrimaryKey(Group record) {
        int rows = getSqlMapClientTemplate().update("lgk_group.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_group
     *
     * @abatorgenerated Mon Aug 03 13:51:36 CDT 2015
     */
    public int updateByPrimaryKeySelective(Group record) {
        int rows = getSqlMapClientTemplate().update("lgk_group.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_group
     *
     * @abatorgenerated Mon Aug 03 13:51:36 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<Group> selectByExample(GroupExample example) {
        List<Group> list = (List<Group>) getSqlMapClientTemplate().queryForList("lgk_group.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_group
     *
     * @abatorgenerated Mon Aug 03 13:51:36 CDT 2015
     */
    public Group selectByPrimaryKey(Long id_group) {
        Group key = new Group();
        key.setId_group(id_group);
        Group record = (Group) getSqlMapClientTemplate().queryForObject("lgk_group.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_group
     *
     * @abatorgenerated Mon Aug 03 13:51:36 CDT 2015
     */
    public int deleteByPrimaryKey(Long id_group) {
        Group key = new Group();
        key.setId_group(id_group);
        int rows = getSqlMapClientTemplate().delete("lgk_group.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_group
     *
     * @abatorgenerated Mon Aug 03 13:51:36 CDT 2015
     */
    public int countByExample(GroupExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_group.abatorgenerated_countByExample", example);
        return count;
    }
}