package com.retailsbs.logistikapp.financial.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.financial.dao.AlmacenDAO;
import com.retailsbs.logistikapp.financial.domain.Almacen;
import com.retailsbs.logistikapp.financial.dto.AlmacenExample;

public class AlmacenDAOImpl extends SqlMapClientDaoSupport implements AlmacenDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_almacen
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public AlmacenDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_almacen
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public Long insert(Almacen record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_almacen.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_almacen
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public int updateByPrimaryKey(Almacen record) {
        int rows = getSqlMapClientTemplate().update("lgk_almacen.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_almacen
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public int updateByPrimaryKeySelective(Almacen record) {
        int rows = getSqlMapClientTemplate().update("lgk_almacen.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_almacen
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    @SuppressWarnings("unchecked")
    public List<Almacen> selectByExample(AlmacenExample example) {
        List<Almacen> list = (List<Almacen>) getSqlMapClientTemplate().queryForList("lgk_almacen.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_almacen
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public Almacen selectByPrimaryKey(Long id_almacen) {
        Almacen key = new Almacen();
        key.setId_almacen(id_almacen);
        Almacen record = (Almacen) getSqlMapClientTemplate().queryForObject("lgk_almacen.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_almacen
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public int deleteByPrimaryKey(Long id_almacen) {
        Almacen key = new Almacen();
        key.setId_almacen(id_almacen);
        int rows = getSqlMapClientTemplate().delete("lgk_almacen.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_almacen
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public int countByExample(AlmacenExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_almacen.abatorgenerated_countByExample", example);
        return count;
    }
}