package com.retailsbs.logistikapp.financial.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.financial.dao.CategoryProductDAO;
import com.retailsbs.logistikapp.financial.domain.CategoryProduct;
import com.retailsbs.logistikapp.financial.dto.CategoryProductExample;

public class CategoryProductDAOImpl extends SqlMapClientDaoSupport implements CategoryProductDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_category_product
     *
     * @abatorgenerated Thu Jul 28 15:23:33 CDT 2016
     */
    public CategoryProductDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_category_product
     *
     * @abatorgenerated Thu Jul 28 15:23:33 CDT 2016
     */
    public Long insert(CategoryProduct record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_category_product.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_category_product
     *
     * @abatorgenerated Thu Jul 28 15:23:33 CDT 2016
     */
    public int updateByPrimaryKey(CategoryProduct record) {
        int rows = getSqlMapClientTemplate().update("lgk_category_product.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_category_product
     *
     * @abatorgenerated Thu Jul 28 15:23:33 CDT 2016
     */
    public int updateByPrimaryKeySelective(CategoryProduct record) {
        int rows = getSqlMapClientTemplate().update("lgk_category_product.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_category_product
     *
     * @abatorgenerated Thu Jul 28 15:23:33 CDT 2016
     */
    @SuppressWarnings("unchecked")
    public List<CategoryProduct> selectByExample(CategoryProductExample example) {
        List<CategoryProduct> list = (List<CategoryProduct>) getSqlMapClientTemplate().queryForList("lgk_category_product.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_category_product
     *
     * @abatorgenerated Thu Jul 28 15:23:33 CDT 2016
     */
    public CategoryProduct selectByPrimaryKey(Long id_category_product) {
        CategoryProduct key = new CategoryProduct();
        key.setId_category_product(id_category_product);
        CategoryProduct record = (CategoryProduct) getSqlMapClientTemplate().queryForObject("lgk_category_product.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_category_product
     *
     * @abatorgenerated Thu Jul 28 15:23:33 CDT 2016
     */
    public int deleteByPrimaryKey(Long id_category_product) {
        CategoryProduct key = new CategoryProduct();
        key.setId_category_product(id_category_product);
        int rows = getSqlMapClientTemplate().delete("lgk_category_product.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_category_product
     *
     * @abatorgenerated Thu Jul 28 15:23:33 CDT 2016
     */
    public int countByExample(CategoryProductExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_category_product.abatorgenerated_countByExample", example);
        return count;
    }
}