package com.retailsbs.logistikapp.financial.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.financial.dao.ConfigurationStockDAO;
import com.retailsbs.logistikapp.financial.domain.ConfigurationStock;
import com.retailsbs.logistikapp.financial.dto.ConfigurationStockExample;

public class ConfigurationStockDAOImpl extends SqlMapClientDaoSupport implements ConfigurationStockDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_configuration_stock
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public ConfigurationStockDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_configuration_stock
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public Long insert(ConfigurationStock record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_configuration_stock.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_configuration_stock
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public int updateByPrimaryKey(ConfigurationStock record) {
        int rows = getSqlMapClientTemplate().update("lgk_configuration_stock.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_configuration_stock
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public int updateByPrimaryKeySelective(ConfigurationStock record) {
        int rows = getSqlMapClientTemplate().update("lgk_configuration_stock.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_configuration_stock
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    @SuppressWarnings("unchecked")
    public List<ConfigurationStock> selectByExample(ConfigurationStockExample example) {
        List<ConfigurationStock> list = (List<ConfigurationStock>) getSqlMapClientTemplate().queryForList("lgk_configuration_stock.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_configuration_stock
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public ConfigurationStock selectByPrimaryKey(Long id_configuration_stock) {
        ConfigurationStock key = new ConfigurationStock();
        key.setId_configuration_stock(id_configuration_stock);
        ConfigurationStock record = (ConfigurationStock) getSqlMapClientTemplate().queryForObject("lgk_configuration_stock.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_configuration_stock
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public int deleteByPrimaryKey(Long id_configuration_stock) {
        ConfigurationStock key = new ConfigurationStock();
        key.setId_configuration_stock(id_configuration_stock);
        int rows = getSqlMapClientTemplate().delete("lgk_configuration_stock.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_configuration_stock
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public int countByExample(ConfigurationStockExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_configuration_stock.abatorgenerated_countByExample", example);
        return count;
    }
}