package com.retailsbs.logistikapp.financial.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.financial.dao.CostDAO;
import com.retailsbs.logistikapp.financial.domain.Cost;
import com.retailsbs.logistikapp.financial.dto.CostExample;

public class CostDAOImpl extends SqlMapClientDaoSupport implements CostDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_cost
     *
     * @abatorgenerated Thu Jul 28 13:53:52 CDT 2016
     */
    public CostDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_cost
     *
     * @abatorgenerated Thu Jul 28 13:53:52 CDT 2016
     */
    public Long insert(Cost record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_cost.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_cost
     *
     * @abatorgenerated Thu Jul 28 13:53:52 CDT 2016
     */
    public int updateByPrimaryKey(Cost record) {
        int rows = getSqlMapClientTemplate().update("lgk_cost.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_cost
     *
     * @abatorgenerated Thu Jul 28 13:53:52 CDT 2016
     */
    public int updateByPrimaryKeySelective(Cost record) {
        int rows = getSqlMapClientTemplate().update("lgk_cost.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_cost
     *
     * @abatorgenerated Thu Jul 28 13:53:52 CDT 2016
     */
    @SuppressWarnings("unchecked")
    public List<Cost> selectByExample(CostExample example) {
        List<Cost> list = (List<Cost>) getSqlMapClientTemplate().queryForList("lgk_cost.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_cost
     *
     * @abatorgenerated Thu Jul 28 13:53:52 CDT 2016
     */
    public Cost selectByPrimaryKey(Long id_cost) {
        Cost key = new Cost();
        key.setId_cost(id_cost);
        Cost record = (Cost) getSqlMapClientTemplate().queryForObject("lgk_cost.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_cost
     *
     * @abatorgenerated Thu Jul 28 13:53:52 CDT 2016
     */
    public int deleteByPrimaryKey(Long id_cost) {
        Cost key = new Cost();
        key.setId_cost(id_cost);
        int rows = getSqlMapClientTemplate().delete("lgk_cost.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_cost
     *
     * @abatorgenerated Thu Jul 28 13:53:52 CDT 2016
     */
    public int countByExample(CostExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_cost.abatorgenerated_countByExample", example);
        return count;
    }
}