package com.retailsbs.logistikapp.financial.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.financial.dao.OrderDetailDAO;
import com.retailsbs.logistikapp.financial.domain.OrderDetail;
import com.retailsbs.logistikapp.financial.dto.OrderDetailExample;

public class OrderDetailDAOImpl extends SqlMapClientDaoSupport implements OrderDetailDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_order_detail
     *
     * @abatorgenerated Tue Oct 03 16:24:25 CDT 2017
     */
    public OrderDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_order_detail
     *
     * @abatorgenerated Tue Oct 03 16:24:25 CDT 2017
     */
    public Long insert(OrderDetail record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_order_detail.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_order_detail
     *
     * @abatorgenerated Tue Oct 03 16:24:25 CDT 2017
     */
    public int updateByPrimaryKey(OrderDetail record) {
        int rows = getSqlMapClientTemplate().update("lgk_order_detail.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_order_detail
     *
     * @abatorgenerated Tue Oct 03 16:24:25 CDT 2017
     */
    public int updateByPrimaryKeySelective(OrderDetail record) {
        int rows = getSqlMapClientTemplate().update("lgk_order_detail.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_order_detail
     *
     * @abatorgenerated Tue Oct 03 16:24:25 CDT 2017
     */
    @SuppressWarnings("unchecked")
    public List<OrderDetail> selectByExample(OrderDetailExample example) {
        List<OrderDetail> list = (List<OrderDetail>) getSqlMapClientTemplate().queryForList("lgk_order_detail.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_order_detail
     *
     * @abatorgenerated Tue Oct 03 16:24:25 CDT 2017
     */
    public OrderDetail selectByPrimaryKey(Long id_order_detail) {
        OrderDetail key = new OrderDetail();
        key.setId_order_detail(id_order_detail);
        OrderDetail record = (OrderDetail) getSqlMapClientTemplate().queryForObject("lgk_order_detail.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_order_detail
     *
     * @abatorgenerated Tue Oct 03 16:24:25 CDT 2017
     */
    public int deleteByPrimaryKey(Long id_order_detail) {
        OrderDetail key = new OrderDetail();
        key.setId_order_detail(id_order_detail);
        int rows = getSqlMapClientTemplate().delete("lgk_order_detail.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_order_detail
     *
     * @abatorgenerated Tue Oct 03 16:24:25 CDT 2017
     */
    public int countByExample(OrderDetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_order_detail.abatorgenerated_countByExample", example);
        return count;
    }
}