package com.retailsbs.logistikapp.financial.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.financial.dao.StoreCategoryProductDAO;
import com.retailsbs.logistikapp.financial.domain.StoreCategoryProduct;
import com.retailsbs.logistikapp.financial.dto.StoreCategoryProductExample;

public class StoreCategoryProductDAOImpl extends SqlMapClientDaoSupport implements StoreCategoryProductDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category_product
     *
     * @abatorgenerated Fri Mar 24 16:07:35 CST 2017
     */
    public StoreCategoryProductDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category_product
     *
     * @abatorgenerated Fri Mar 24 16:07:35 CST 2017
     */
    public Long insert(StoreCategoryProduct record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_store_category_product.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category_product
     *
     * @abatorgenerated Fri Mar 24 16:07:35 CST 2017
     */
    public int updateByPrimaryKey(StoreCategoryProduct record) {
        int rows = getSqlMapClientTemplate().update("lgk_store_category_product.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category_product
     *
     * @abatorgenerated Fri Mar 24 16:07:35 CST 2017
     */
    public int updateByPrimaryKeySelective(StoreCategoryProduct record) {
        int rows = getSqlMapClientTemplate().update("lgk_store_category_product.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category_product
     *
     * @abatorgenerated Fri Mar 24 16:07:35 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<StoreCategoryProduct> selectByExample(StoreCategoryProductExample example) {
        List<StoreCategoryProduct> list = (List<StoreCategoryProduct>) getSqlMapClientTemplate().queryForList("lgk_store_category_product.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category_product
     *
     * @abatorgenerated Fri Mar 24 16:07:35 CST 2017
     */
    public StoreCategoryProduct selectByPrimaryKey(Long id_store_category_product) {
        StoreCategoryProduct key = new StoreCategoryProduct();
        key.setId_store_category_product(id_store_category_product);
        StoreCategoryProduct record = (StoreCategoryProduct) getSqlMapClientTemplate().queryForObject("lgk_store_category_product.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category_product
     *
     * @abatorgenerated Fri Mar 24 16:07:35 CST 2017
     */
    public int deleteByPrimaryKey(Long id_store_category_product) {
        StoreCategoryProduct key = new StoreCategoryProduct();
        key.setId_store_category_product(id_store_category_product);
        int rows = getSqlMapClientTemplate().delete("lgk_store_category_product.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_store_category_product
     *
     * @abatorgenerated Fri Mar 24 16:07:35 CST 2017
     */
    public int countByExample(StoreCategoryProductExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_store_category_product.abatorgenerated_countByExample", example);
        return count;
    }
}