package com.retailsbs.logistikapp.domain.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.domain.dao.DomainDAO;
import com.retailsbs.logistikapp.domain.domain.Domain;
import com.retailsbs.logistikapp.domain.dto.DomainExample;

public class DomainDAOImpl extends SqlMapClientDaoSupport implements DomainDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_domain
     *
     * @abatorgenerated Mon Nov 24 09:51:26 CST 2014
     */
    public DomainDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_domain
     *
     * @abatorgenerated Mon Nov 24 09:51:26 CST 2014
     */
    public Long insert(Domain record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_domain.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_domain
     *
     * @abatorgenerated Mon Nov 24 09:51:26 CST 2014
     */
    public int updateByPrimaryKey(Domain record) {
        int rows = getSqlMapClientTemplate().update("lgk_domain.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_domain
     *
     * @abatorgenerated Mon Nov 24 09:51:26 CST 2014
     */
    public int updateByPrimaryKeySelective(Domain record) {
        int rows = getSqlMapClientTemplate().update("lgk_domain.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_domain
     *
     * @abatorgenerated Mon Nov 24 09:51:26 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<Domain> selectByExample(DomainExample example) {
        List<Domain> list = (List<Domain>) getSqlMapClientTemplate().queryForList("lgk_domain.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_domain
     *
     * @abatorgenerated Mon Nov 24 09:51:26 CST 2014
     */
    public Domain selectByPrimaryKey(Long id_domain) {
        Domain key = new Domain();
        key.setId_domain(id_domain);
        Domain record = (Domain) getSqlMapClientTemplate().queryForObject("lgk_domain.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_domain
     *
     * @abatorgenerated Mon Nov 24 09:51:26 CST 2014
     */
    public int deleteByPrimaryKey(Long id_domain) {
        Domain key = new Domain();
        key.setId_domain(id_domain);
        int rows = getSqlMapClientTemplate().delete("lgk_domain.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_domain
     *
     * @abatorgenerated Mon Nov 24 09:51:26 CST 2014
     */
    public int countByExample(DomainExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_domain.abatorgenerated_countByExample", example);
        return count;
    }
}