package com.retailsbs.logistikapp.financial.domain;

public class ConfigurationStockProduct {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_configuration_stock_product.id_configuration_stock_product
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    private Long id_configuration_stock_product;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_configuration_stock_product.id_configuration_stock
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    private Long id_configuration_stock;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_configuration_stock_product.id_product
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    private Long id_product;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_configuration_stock_product.min
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    private Long min;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_configuration_stock_product.max
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    private Long max;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_configuration_stock_product.qty
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    private Long qty;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_configuration_stock_product.id_configuration_stock_product
     *
     * @return the value of lgk_configuration_stock_product.id_configuration_stock_product
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public Long getId_configuration_stock_product() {
        return id_configuration_stock_product;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_configuration_stock_product.id_configuration_stock_product
     *
     * @param id_configuration_stock_product the value for lgk_configuration_stock_product.id_configuration_stock_product
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public void setId_configuration_stock_product(Long id_configuration_stock_product) {
        this.id_configuration_stock_product = id_configuration_stock_product;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_configuration_stock_product.id_configuration_stock
     *
     * @return the value of lgk_configuration_stock_product.id_configuration_stock
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public Long getId_configuration_stock() {
        return id_configuration_stock;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_configuration_stock_product.id_configuration_stock
     *
     * @param id_configuration_stock the value for lgk_configuration_stock_product.id_configuration_stock
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public void setId_configuration_stock(Long id_configuration_stock) {
        this.id_configuration_stock = id_configuration_stock;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_configuration_stock_product.id_product
     *
     * @return the value of lgk_configuration_stock_product.id_product
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public Long getId_product() {
        return id_product;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_configuration_stock_product.id_product
     *
     * @param id_product the value for lgk_configuration_stock_product.id_product
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public void setId_product(Long id_product) {
        this.id_product = id_product;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_configuration_stock_product.min
     *
     * @return the value of lgk_configuration_stock_product.min
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public Long getMin() {
        return min;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_configuration_stock_product.min
     *
     * @param min the value for lgk_configuration_stock_product.min
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public void setMin(Long min) {
        this.min = min;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_configuration_stock_product.max
     *
     * @return the value of lgk_configuration_stock_product.max
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public Long getMax() {
        return max;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_configuration_stock_product.max
     *
     * @param max the value for lgk_configuration_stock_product.max
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public void setMax(Long max) {
        this.max = max;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_configuration_stock_product.qty
     *
     * @return the value of lgk_configuration_stock_product.qty
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public Long getQty() {
        return qty;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_configuration_stock_product.qty
     *
     * @param qty the value for lgk_configuration_stock_product.qty
     *
     * @abatorgenerated Thu Aug 31 11:31:38 CDT 2017
     */
    public void setQty(Long qty) {
        this.qty = qty;
    }
}