package com.retailsbs.logistikapp.user.domain;

import java.util.Date;

public class UserMessage {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_user_message.id_user_message
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    private Long id_user_message;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_user_message.id_user
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    private Long id_user;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_user_message.id_user_to
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    private Long id_user_to;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_user_message.created
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    private Date created;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_user_message.id_user_message
     *
     * @return the value of lgk_user_message.id_user_message
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public Long getId_user_message() {
        return id_user_message;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_user_message.id_user_message
     *
     * @param id_user_message the value for lgk_user_message.id_user_message
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public void setId_user_message(Long id_user_message) {
        this.id_user_message = id_user_message;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_user_message.id_user
     *
     * @return the value of lgk_user_message.id_user
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public Long getId_user() {
        return id_user;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_user_message.id_user
     *
     * @param id_user the value for lgk_user_message.id_user
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public void setId_user(Long id_user) {
        this.id_user = id_user;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_user_message.id_user_to
     *
     * @return the value of lgk_user_message.id_user_to
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public Long getId_user_to() {
        return id_user_to;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_user_message.id_user_to
     *
     * @param id_user_to the value for lgk_user_message.id_user_to
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public void setId_user_to(Long id_user_to) {
        this.id_user_to = id_user_to;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_user_message.created
     *
     * @return the value of lgk_user_message.created
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_user_message.created
     *
     * @param created the value for lgk_user_message.created
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}