package com.retailsbs.logistikapp.retail.domain;

import java.util.Date;

public class State {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_state.id_state
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    private Long id_state;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_state.id_country
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    private Long id_country;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_state.created
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    private Date created;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_state.modified
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    private Date modified;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_state.login
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    private String login;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_state.orderby
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    private Integer orderby;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_state.active
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    private String active;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_state.code
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    private String code;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_state.prefix
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    private String prefix;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_state.name
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    private String name;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_state.id_state
     *
     * @return the value of lgk_state.id_state
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public Long getId_state() {
        return id_state;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_state.id_state
     *
     * @param id_state the value for lgk_state.id_state
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public void setId_state(Long id_state) {
        this.id_state = id_state;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_state.id_country
     *
     * @return the value of lgk_state.id_country
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public Long getId_country() {
        return id_country;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_state.id_country
     *
     * @param id_country the value for lgk_state.id_country
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public void setId_country(Long id_country) {
        this.id_country = id_country;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_state.created
     *
     * @return the value of lgk_state.created
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_state.created
     *
     * @param created the value for lgk_state.created
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_state.modified
     *
     * @return the value of lgk_state.modified
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_state.modified
     *
     * @param modified the value for lgk_state.modified
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_state.login
     *
     * @return the value of lgk_state.login
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_state.login
     *
     * @param login the value for lgk_state.login
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_state.orderby
     *
     * @return the value of lgk_state.orderby
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_state.orderby
     *
     * @param orderby the value for lgk_state.orderby
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_state.active
     *
     * @return the value of lgk_state.active
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_state.active
     *
     * @param active the value for lgk_state.active
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public void setActive(String active) {
        this.active = active;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_state.code
     *
     * @return the value of lgk_state.code
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_state.code
     *
     * @param code the value for lgk_state.code
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_state.prefix
     *
     * @return the value of lgk_state.prefix
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_state.prefix
     *
     * @param prefix the value for lgk_state.prefix
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_state.name
     *
     * @return the value of lgk_state.name
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_state.name
     *
     * @param name the value for lgk_state.name
     *
     * @abatorgenerated Thu Nov 20 16:35:37 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }
}