package com.retailsbs.logistikapp.financial.dao;

import java.util.List;

import com.retailsbs.logistikapp.financial.domain.ProductAlmacen;
import com.retailsbs.logistikapp.financial.dto.ProductAlmacenExample;

public interface ProductAlmacenDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product_almacen
     *
     * @abatorgenerated Fri Oct 06 10:47:10 CDT 2017
     */
    Long insert(ProductAlmacen record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product_almacen
     *
     * @abatorgenerated Fri Oct 06 10:47:10 CDT 2017
     */
    int updateByPrimaryKey(ProductAlmacen record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product_almacen
     *
     * @abatorgenerated Fri Oct 06 10:47:10 CDT 2017
     */
    int updateByPrimaryKeySelective(ProductAlmacen record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product_almacen
     *
     * @abatorgenerated Fri Oct 06 10:47:10 CDT 2017
     */
    List<ProductAlmacen> selectByExample(ProductAlmacenExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product_almacen
     *
     * @abatorgenerated Fri Oct 06 10:47:10 CDT 2017
     */
    ProductAlmacen selectByPrimaryKey(Long id_product_almacen);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product_almacen
     *
     * @abatorgenerated Fri Oct 06 10:47:10 CDT 2017
     */
    int deleteByPrimaryKey(Long id_product_almacen);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_product_almacen
     *
     * @abatorgenerated Fri Oct 06 10:47:10 CDT 2017
     */
    int countByExample(ProductAlmacenExample example);
}