package com.retailsbs.logistikapp.supplier.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.supplier.dao.PlanDAO;
import com.retailsbs.logistikapp.supplier.domain.Plan;
import com.retailsbs.logistikapp.supplier.dto.PlanExample;

public class PlanDAOImpl extends SqlMapClientDaoSupport implements PlanDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    public PlanDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    public Long insert(Plan record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_plan.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    public int updateByPrimaryKey(Plan record) {
        int rows = getSqlMapClientTemplate().update("lgk_plan.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    public int updateByPrimaryKeySelective(Plan record) {
        int rows = getSqlMapClientTemplate().update("lgk_plan.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<Plan> selectByExample(PlanExample example) {
        List<Plan> list = (List<Plan>) getSqlMapClientTemplate().queryForList("lgk_plan.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    public Plan selectByPrimaryKey(Long id_plan) {
        Plan key = new Plan();
        key.setId_plan(id_plan);
        Plan record = (Plan) getSqlMapClientTemplate().queryForObject("lgk_plan.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    public int deleteByExample(PlanExample example) {
        int rows = getSqlMapClientTemplate().delete("lgk_plan.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    public int deleteByPrimaryKey(Long id_plan) {
        Plan key = new Plan();
        key.setId_plan(id_plan);
        int rows = getSqlMapClientTemplate().delete("lgk_plan.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    public int countByExample(PlanExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_plan.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    public int updateByExampleSelective(Plan record, PlanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("lgk_plan.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    public int updateByExample(Plan record, PlanExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("lgk_plan.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table lgk_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:15 CST 2016
     */
    private static class UpdateByExampleParms extends PlanExample {
        public UpdateByExampleParms(Object record, PlanExample example) {
            super(example);
        }
    }
}