package com.retailsbs.logistikapp.supplier.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.supplier.dao.SupplierDAO;
import com.retailsbs.logistikapp.supplier.domain.Supplier;
import com.retailsbs.logistikapp.supplier.dto.SupplierExample;

public class SupplierDAOImpl extends SqlMapClientDaoSupport implements SupplierDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_supplier
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public SupplierDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_supplier
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Long insert(Supplier record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_supplier.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_supplier
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public int updateByPrimaryKey(Supplier record) {
        int rows = getSqlMapClientTemplate().update("lgk_supplier.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_supplier
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public int updateByPrimaryKeySelective(Supplier record) {
        int rows = getSqlMapClientTemplate().update("lgk_supplier.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_supplier
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    @SuppressWarnings("unchecked")
    public List<Supplier> selectByExample(SupplierExample example) {
        List<Supplier> list = (List<Supplier>) getSqlMapClientTemplate().queryForList("lgk_supplier.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_supplier
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Supplier selectByPrimaryKey(Long id_supplier) {
        Supplier key = new Supplier();
        key.setId_supplier(id_supplier);
        Supplier record = (Supplier) getSqlMapClientTemplate().queryForObject("lgk_supplier.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_supplier
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public int deleteByPrimaryKey(Long id_supplier) {
        Supplier key = new Supplier();
        key.setId_supplier(id_supplier);
        int rows = getSqlMapClientTemplate().delete("lgk_supplier.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_supplier
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public int countByExample(SupplierExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_supplier.abatorgenerated_countByExample", example);
        return count;
    }
}