package com.retailsbs.logistikapp.user.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.user.dao.MessageGroupDAO;
import com.retailsbs.logistikapp.user.domain.MessageGroup;
import com.retailsbs.logistikapp.user.dto.MessageGroupExample;

public class MessageGroupDAOImpl extends SqlMapClientDaoSupport implements MessageGroupDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_message_group
     *
     * @abatorgenerated Mon Aug 03 13:53:13 CDT 2015
     */
    public MessageGroupDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_message_group
     *
     * @abatorgenerated Mon Aug 03 13:53:13 CDT 2015
     */
    public Long insert(MessageGroup record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_message_group.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_message_group
     *
     * @abatorgenerated Mon Aug 03 13:53:13 CDT 2015
     */
    public int updateByPrimaryKey(MessageGroup record) {
        int rows = getSqlMapClientTemplate().update("lgk_message_group.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_message_group
     *
     * @abatorgenerated Mon Aug 03 13:53:13 CDT 2015
     */
    public int updateByPrimaryKeySelective(MessageGroup record) {
        int rows = getSqlMapClientTemplate().update("lgk_message_group.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_message_group
     *
     * @abatorgenerated Mon Aug 03 13:53:13 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<MessageGroup> selectByExample(MessageGroupExample example) {
        List<MessageGroup> list = (List<MessageGroup>) getSqlMapClientTemplate().queryForList("lgk_message_group.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_message_group
     *
     * @abatorgenerated Mon Aug 03 13:53:13 CDT 2015
     */
    public MessageGroup selectByPrimaryKey(Long id_message_group) {
        MessageGroup key = new MessageGroup();
        key.setId_message_group(id_message_group);
        MessageGroup record = (MessageGroup) getSqlMapClientTemplate().queryForObject("lgk_message_group.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_message_group
     *
     * @abatorgenerated Mon Aug 03 13:53:13 CDT 2015
     */
    public int deleteByPrimaryKey(Long id_message_group) {
        MessageGroup key = new MessageGroup();
        key.setId_message_group(id_message_group);
        int rows = getSqlMapClientTemplate().delete("lgk_message_group.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_message_group
     *
     * @abatorgenerated Mon Aug 03 13:53:13 CDT 2015
     */
    public int countByExample(MessageGroupExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_message_group.abatorgenerated_countByExample", example);
        return count;
    }
}