package com.retailsbs.logistikapp.user.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.user.dao.UserGroupDAO;
import com.retailsbs.logistikapp.user.domain.UserGroup;
import com.retailsbs.logistikapp.user.dto.UserGroupExample;

public class UserGroupDAOImpl extends SqlMapClientDaoSupport implements UserGroupDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_group
     *
     * @abatorgenerated Mon Aug 03 13:53:45 CDT 2015
     */
    public UserGroupDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_group
     *
     * @abatorgenerated Mon Aug 03 13:53:45 CDT 2015
     */
    public Long insert(UserGroup record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_user_group.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_group
     *
     * @abatorgenerated Mon Aug 03 13:53:45 CDT 2015
     */
    public int updateByPrimaryKey(UserGroup record) {
        int rows = getSqlMapClientTemplate().update("lgk_user_group.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_group
     *
     * @abatorgenerated Mon Aug 03 13:53:45 CDT 2015
     */
    public int updateByPrimaryKeySelective(UserGroup record) {
        int rows = getSqlMapClientTemplate().update("lgk_user_group.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_group
     *
     * @abatorgenerated Mon Aug 03 13:53:45 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<UserGroup> selectByExample(UserGroupExample example) {
        List<UserGroup> list = (List<UserGroup>) getSqlMapClientTemplate().queryForList("lgk_user_group.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_group
     *
     * @abatorgenerated Mon Aug 03 13:53:45 CDT 2015
     */
    public UserGroup selectByPrimaryKey(Long id_user_group) {
        UserGroup key = new UserGroup();
        key.setId_user_group(id_user_group);
        UserGroup record = (UserGroup) getSqlMapClientTemplate().queryForObject("lgk_user_group.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_group
     *
     * @abatorgenerated Mon Aug 03 13:53:45 CDT 2015
     */
    public int deleteByPrimaryKey(Long id_user_group) {
        UserGroup key = new UserGroup();
        key.setId_user_group(id_user_group);
        int rows = getSqlMapClientTemplate().delete("lgk_user_group.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_group
     *
     * @abatorgenerated Mon Aug 03 13:53:45 CDT 2015
     */
    public int countByExample(UserGroupExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_user_group.abatorgenerated_countByExample", example);
        return count;
    }
}