package com.retailsbs.logistikapp.user.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.user.dao.UserMessageDAO;
import com.retailsbs.logistikapp.user.domain.UserMessage;
import com.retailsbs.logistikapp.user.dto.UserMessageExample;

public class UserMessageDAOImpl extends SqlMapClientDaoSupport implements UserMessageDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_message
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public UserMessageDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_message
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public Long insert(UserMessage record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_user_message.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_message
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public int updateByPrimaryKey(UserMessage record) {
        int rows = getSqlMapClientTemplate().update("lgk_user_message.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_message
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public int updateByPrimaryKeySelective(UserMessage record) {
        int rows = getSqlMapClientTemplate().update("lgk_user_message.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_message
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    @SuppressWarnings("unchecked")
    public List<UserMessage> selectByExample(UserMessageExample example) {
        List<UserMessage> list = (List<UserMessage>) getSqlMapClientTemplate().queryForList("lgk_user_message.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_message
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public UserMessage selectByPrimaryKey(Long id_user_message) {
        UserMessage key = new UserMessage();
        key.setId_user_message(id_user_message);
        UserMessage record = (UserMessage) getSqlMapClientTemplate().queryForObject("lgk_user_message.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_message
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public int deleteByPrimaryKey(Long id_user_message) {
        UserMessage key = new UserMessage();
        key.setId_user_message(id_user_message);
        int rows = getSqlMapClientTemplate().delete("lgk_user_message.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_message
     *
     * @abatorgenerated Wed Jan 07 14:28:15 CST 2015
     */
    public int countByExample(UserMessageExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_user_message.abatorgenerated_countByExample", example);
        return count;
    }
}