package com.retailsbs.logistikapp.logistic.dao;

import java.util.List;

import com.retailsbs.logistikapp.logistic.domain.WayBill;
import com.retailsbs.logistikapp.logistic.dto.WayBillExample;

public interface WayBillDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    Long insert(WayBill record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    int updateByPrimaryKey(WayBill record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    int updateByPrimaryKeySelective(WayBill record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    List<WayBill> selectByExample(WayBillExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    WayBill selectByPrimaryKey(Long id_waybill);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    int deleteByPrimaryKey(Long id_waybill);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    int countByExample(WayBillExample example);
}