package com.retailsbs.logistikapp.supplier.domain;

public class Plan {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.id_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private Long id_plan;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.plan_name
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private String plan_name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.customers
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private Long customers;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.users
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private Long users;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.searchbox
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private String searchbox;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.scheduling
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private String scheduling;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.routes
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private String routes;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.travels
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private String travels;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.historical
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private String historical;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.callcenter
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private String callcenter;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.notifications
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private String notifications;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.messages
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private String messages;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.groups
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private String groups;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.tasks
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private String tasks;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_plan.amount
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    private Long amount;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.id_plan
     *
     * @return the value of lgk_plan.id_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public Long getId_plan() {
        return id_plan;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.id_plan
     *
     * @param id_plan the value for lgk_plan.id_plan
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setId_plan(Long id_plan) {
        this.id_plan = id_plan;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.plan_name
     *
     * @return the value of lgk_plan.plan_name
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public String getPlan_name() {
        return plan_name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.plan_name
     *
     * @param plan_name the value for lgk_plan.plan_name
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setPlan_name(String plan_name) {
        this.plan_name = plan_name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.customers
     *
     * @return the value of lgk_plan.customers
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public Long getCustomers() {
        return customers;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.customers
     *
     * @param customers the value for lgk_plan.customers
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setCustomers(Long customers) {
        this.customers = customers;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.users
     *
     * @return the value of lgk_plan.users
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public Long getUsers() {
        return users;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.users
     *
     * @param users the value for lgk_plan.users
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setUsers(Long users) {
        this.users = users;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.searchbox
     *
     * @return the value of lgk_plan.searchbox
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public String getSearchbox() {
        return searchbox;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.searchbox
     *
     * @param searchbox the value for lgk_plan.searchbox
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setSearchbox(String searchbox) {
        this.searchbox = searchbox;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.scheduling
     *
     * @return the value of lgk_plan.scheduling
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public String getScheduling() {
        return scheduling;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.scheduling
     *
     * @param scheduling the value for lgk_plan.scheduling
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setScheduling(String scheduling) {
        this.scheduling = scheduling;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.routes
     *
     * @return the value of lgk_plan.routes
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public String getRoutes() {
        return routes;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.routes
     *
     * @param routes the value for lgk_plan.routes
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setRoutes(String routes) {
        this.routes = routes;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.travels
     *
     * @return the value of lgk_plan.travels
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public String getTravels() {
        return travels;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.travels
     *
     * @param travels the value for lgk_plan.travels
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setTravels(String travels) {
        this.travels = travels;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.historical
     *
     * @return the value of lgk_plan.historical
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public String getHistorical() {
        return historical;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.historical
     *
     * @param historical the value for lgk_plan.historical
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setHistorical(String historical) {
        this.historical = historical;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.callcenter
     *
     * @return the value of lgk_plan.callcenter
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public String getCallcenter() {
        return callcenter;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.callcenter
     *
     * @param callcenter the value for lgk_plan.callcenter
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setCallcenter(String callcenter) {
        this.callcenter = callcenter;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.notifications
     *
     * @return the value of lgk_plan.notifications
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public String getNotifications() {
        return notifications;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.notifications
     *
     * @param notifications the value for lgk_plan.notifications
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setNotifications(String notifications) {
        this.notifications = notifications;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.messages
     *
     * @return the value of lgk_plan.messages
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public String getMessages() {
        return messages;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.messages
     *
     * @param messages the value for lgk_plan.messages
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setMessages(String messages) {
        this.messages = messages;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.groups
     *
     * @return the value of lgk_plan.groups
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public String getGroups() {
        return groups;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.groups
     *
     * @param groups the value for lgk_plan.groups
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setGroups(String groups) {
        this.groups = groups;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.tasks
     *
     * @return the value of lgk_plan.tasks
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public String getTasks() {
        return tasks;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.tasks
     *
     * @param tasks the value for lgk_plan.tasks
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setTasks(String tasks) {
        this.tasks = tasks;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_plan.amount
     *
     * @return the value of lgk_plan.amount
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_plan.amount
     *
     * @param amount the value for lgk_plan.amount
     *
     * @abatorgenerated Tue Mar 08 08:30:16 CST 2016
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }
}