package com.retailsbs.logistikapp.supplier.domain;

import java.util.Date;

public class Supplier {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.id_supplier
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private Long id_supplier;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.created
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private Date created;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.modified
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private Date modified;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.login
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private String login;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.orderby
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private Integer orderby;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.active
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private String active;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.code
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private String code;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.name
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.id_plan
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private Long id_plan;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.plan_created
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private Date plan_created;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.plan_started
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private Date plan_started;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.plan_end
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private Date plan_end;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.payment
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private String payment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.adjustment
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private Double adjustment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.unpaid
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private Long unpaid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.shelf
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private String shelf;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column lgk_supplier.travel_time
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    private Long travel_time;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.id_supplier
     *
     * @return the value of lgk_supplier.id_supplier
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Long getId_supplier() {
        return id_supplier;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.id_supplier
     *
     * @param id_supplier the value for lgk_supplier.id_supplier
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setId_supplier(Long id_supplier) {
        this.id_supplier = id_supplier;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.created
     *
     * @return the value of lgk_supplier.created
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.created
     *
     * @param created the value for lgk_supplier.created
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.modified
     *
     * @return the value of lgk_supplier.modified
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.modified
     *
     * @param modified the value for lgk_supplier.modified
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.login
     *
     * @return the value of lgk_supplier.login
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.login
     *
     * @param login the value for lgk_supplier.login
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.orderby
     *
     * @return the value of lgk_supplier.orderby
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.orderby
     *
     * @param orderby the value for lgk_supplier.orderby
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.active
     *
     * @return the value of lgk_supplier.active
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.active
     *
     * @param active the value for lgk_supplier.active
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setActive(String active) {
        this.active = active;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.code
     *
     * @return the value of lgk_supplier.code
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.code
     *
     * @param code the value for lgk_supplier.code
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.name
     *
     * @return the value of lgk_supplier.name
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.name
     *
     * @param name the value for lgk_supplier.name
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.id_plan
     *
     * @return the value of lgk_supplier.id_plan
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Long getId_plan() {
        return id_plan;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.id_plan
     *
     * @param id_plan the value for lgk_supplier.id_plan
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setId_plan(Long id_plan) {
        this.id_plan = id_plan;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.plan_created
     *
     * @return the value of lgk_supplier.plan_created
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Date getPlan_created() {
        return plan_created;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.plan_created
     *
     * @param plan_created the value for lgk_supplier.plan_created
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setPlan_created(Date plan_created) {
        this.plan_created = plan_created;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.plan_started
     *
     * @return the value of lgk_supplier.plan_started
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Date getPlan_started() {
        return plan_started;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.plan_started
     *
     * @param plan_started the value for lgk_supplier.plan_started
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setPlan_started(Date plan_started) {
        this.plan_started = plan_started;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.plan_end
     *
     * @return the value of lgk_supplier.plan_end
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Date getPlan_end() {
        return plan_end;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.plan_end
     *
     * @param plan_end the value for lgk_supplier.plan_end
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setPlan_end(Date plan_end) {
        this.plan_end = plan_end;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.payment
     *
     * @return the value of lgk_supplier.payment
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.payment
     *
     * @param payment the value for lgk_supplier.payment
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setPayment(String payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.adjustment
     *
     * @return the value of lgk_supplier.adjustment
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Double getAdjustment() {
        return adjustment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.adjustment
     *
     * @param adjustment the value for lgk_supplier.adjustment
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setAdjustment(Double adjustment) {
        this.adjustment = adjustment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.unpaid
     *
     * @return the value of lgk_supplier.unpaid
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Long getUnpaid() {
        return unpaid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.unpaid
     *
     * @param unpaid the value for lgk_supplier.unpaid
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setUnpaid(Long unpaid) {
        this.unpaid = unpaid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.shelf
     *
     * @return the value of lgk_supplier.shelf
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public String getShelf() {
        return shelf;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.shelf
     *
     * @param shelf the value for lgk_supplier.shelf
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setShelf(String shelf) {
        this.shelf = shelf;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column lgk_supplier.travel_time
     *
     * @return the value of lgk_supplier.travel_time
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public Long getTravel_time() {
        return travel_time;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column lgk_supplier.travel_time
     *
     * @param travel_time the value for lgk_supplier.travel_time
     *
     * @abatorgenerated Fri Apr 08 12:37:47 CDT 2016
     */
    public void setTravel_time(Long travel_time) {
        this.travel_time = travel_time;
    }
}