package com.retailsbs.logistikapp.user.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AttachmentExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public AttachmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table lgk_attachment
     *
     * @abatorgenerated Mon Aug 03 13:39:53 CDT 2015
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andId_attachmentIsNull() {
            addCriterion("id_attachment is null");
            return this;
        }

        public Criteria andId_attachmentIsNotNull() {
            addCriterion("id_attachment is not null");
            return this;
        }

        public Criteria andId_attachmentEqualTo(Long value) {
            addCriterion("id_attachment =", value, "id_attachment");
            return this;
        }

        public Criteria andId_attachmentNotEqualTo(Long value) {
            addCriterion("id_attachment <>", value, "id_attachment");
            return this;
        }

        public Criteria andId_attachmentGreaterThan(Long value) {
            addCriterion("id_attachment >", value, "id_attachment");
            return this;
        }

        public Criteria andId_attachmentGreaterThanOrEqualTo(Long value) {
            addCriterion("id_attachment >=", value, "id_attachment");
            return this;
        }

        public Criteria andId_attachmentLessThan(Long value) {
            addCriterion("id_attachment <", value, "id_attachment");
            return this;
        }

        public Criteria andId_attachmentLessThanOrEqualTo(Long value) {
            addCriterion("id_attachment <=", value, "id_attachment");
            return this;
        }

        public Criteria andId_attachmentIn(List<Long> values) {
            addCriterion("id_attachment in", values, "id_attachment");
            return this;
        }

        public Criteria andId_attachmentNotIn(List<Long> values) {
            addCriterion("id_attachment not in", values, "id_attachment");
            return this;
        }

        public Criteria andId_attachmentBetween(Long value1, Long value2) {
            addCriterion("id_attachment between", value1, value2, "id_attachment");
            return this;
        }

        public Criteria andId_attachmentNotBetween(Long value1, Long value2) {
            addCriterion("id_attachment not between", value1, value2, "id_attachment");
            return this;
        }

        public Criteria andId_messageIsNull() {
            addCriterion("id_message is null");
            return this;
        }

        public Criteria andId_messageIsNotNull() {
            addCriterion("id_message is not null");
            return this;
        }

        public Criteria andId_messageEqualTo(Long value) {
            addCriterion("id_message =", value, "id_message");
            return this;
        }

        public Criteria andId_messageNotEqualTo(Long value) {
            addCriterion("id_message <>", value, "id_message");
            return this;
        }

        public Criteria andId_messageGreaterThan(Long value) {
            addCriterion("id_message >", value, "id_message");
            return this;
        }

        public Criteria andId_messageGreaterThanOrEqualTo(Long value) {
            addCriterion("id_message >=", value, "id_message");
            return this;
        }

        public Criteria andId_messageLessThan(Long value) {
            addCriterion("id_message <", value, "id_message");
            return this;
        }

        public Criteria andId_messageLessThanOrEqualTo(Long value) {
            addCriterion("id_message <=", value, "id_message");
            return this;
        }

        public Criteria andId_messageIn(List<Long> values) {
            addCriterion("id_message in", values, "id_message");
            return this;
        }

        public Criteria andId_messageNotIn(List<Long> values) {
            addCriterion("id_message not in", values, "id_message");
            return this;
        }

        public Criteria andId_messageBetween(Long value1, Long value2) {
            addCriterion("id_message between", value1, value2, "id_message");
            return this;
        }

        public Criteria andId_messageNotBetween(Long value1, Long value2) {
            addCriterion("id_message not between", value1, value2, "id_message");
            return this;
        }

        public Criteria andFileIsNull() {
            addCriterion("file is null");
            return this;
        }

        public Criteria andFileIsNotNull() {
            addCriterion("file is not null");
            return this;
        }

        public Criteria andFileEqualTo(String value) {
            addCriterion("file =", value, "file");
            return this;
        }

        public Criteria andFileNotEqualTo(String value) {
            addCriterion("file <>", value, "file");
            return this;
        }

        public Criteria andFileGreaterThan(String value) {
            addCriterion("file >", value, "file");
            return this;
        }

        public Criteria andFileGreaterThanOrEqualTo(String value) {
            addCriterion("file >=", value, "file");
            return this;
        }

        public Criteria andFileLessThan(String value) {
            addCriterion("file <", value, "file");
            return this;
        }

        public Criteria andFileLessThanOrEqualTo(String value) {
            addCriterion("file <=", value, "file");
            return this;
        }

        public Criteria andFileLike(String value) {
            addCriterion("file like", value, "file");
            return this;
        }

        public Criteria andFileNotLike(String value) {
            addCriterion("file not like", value, "file");
            return this;
        }

        public Criteria andFileIn(List<String> values) {
            addCriterion("file in", values, "file");
            return this;
        }

        public Criteria andFileNotIn(List<String> values) {
            addCriterion("file not in", values, "file");
            return this;
        }

        public Criteria andFileBetween(String value1, String value2) {
            addCriterion("file between", value1, value2, "file");
            return this;
        }

        public Criteria andFileNotBetween(String value1, String value2) {
            addCriterion("file not between", value1, value2, "file");
            return this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("created =", value, "created");
            return this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("created <>", value, "created");
            return this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("created >", value, "created");
            return this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("created >=", value, "created");
            return this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("created <", value, "created");
            return this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("created <=", value, "created");
            return this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("created in", values, "created");
            return this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("created not in", values, "created");
            return this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("created between", value1, value2, "created");
            return this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("created not between", value1, value2, "created");
            return this;
        }
    }
}