package com.retailsbs.logistikapp.user.notification.dao;

import java.util.List;
import com.retailsbs.logistikapp.user.notification.domain.UserNotification;
import com.retailsbs.logistikapp.user.notification.domain.UserNotificationExample;

public interface UserNotificationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_notification
     *
     * @abatorgenerated Fri May 20 09:11:21 CDT 2016
     */
    Long insert(UserNotification record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_notification
     *
     * @abatorgenerated Fri May 20 09:11:21 CDT 2016
     */
    int updateByPrimaryKey(UserNotification record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_notification
     *
     * @abatorgenerated Fri May 20 09:11:21 CDT 2016
     */
    int updateByPrimaryKeySelective(UserNotification record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_notification
     *
     * @abatorgenerated Fri May 20 09:11:21 CDT 2016
     */
    List<UserNotification> selectByExample(UserNotificationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_notification
     *
     * @abatorgenerated Fri May 20 09:11:21 CDT 2016
     */
    UserNotification selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_notification
     *
     * @abatorgenerated Fri May 20 09:11:21 CDT 2016
     */
    int deleteByExample(UserNotificationExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_notification
     *
     * @abatorgenerated Fri May 20 09:11:21 CDT 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_notification
     *
     * @abatorgenerated Fri May 20 09:11:21 CDT 2016
     */
    int countByExample(UserNotificationExample example);
}