package com.retailsbs.logistikapp.logistic.dao.ibatis;

import com.retailsbs.logistikapp.logistic.domain.RouteStore;
import com.retailsbs.logistikapp.logistic.dto.RouteStoreExample;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.logistic.dao.RouteStoreDAO;

public class RouteStoreDAOImpl extends SqlMapClientDaoSupport implements RouteStoreDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_route_store
     *
     * @abatorgenerated Thu Sep 03 10:12:15 CDT 2015
     */
    public RouteStoreDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_route_store
     *
     * @abatorgenerated Thu Sep 03 10:12:15 CDT 2015
     */
    public Long insert(RouteStore record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_route_store.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_route_store
     *
     * @abatorgenerated Thu Sep 03 10:12:15 CDT 2015
     */
    public int updateByPrimaryKey(RouteStore record) {
        int rows = getSqlMapClientTemplate().update("lgk_route_store.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_route_store
     *
     * @abatorgenerated Thu Sep 03 10:12:15 CDT 2015
     */
    public int updateByPrimaryKeySelective(RouteStore record) {
        int rows = getSqlMapClientTemplate().update("lgk_route_store.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_route_store
     *
     * @abatorgenerated Thu Sep 03 10:12:15 CDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<RouteStore> selectByExample(RouteStoreExample example) {
        List<RouteStore> list = (List<RouteStore>) getSqlMapClientTemplate().queryForList("lgk_route_store.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_route_store
     *
     * @abatorgenerated Thu Sep 03 10:12:15 CDT 2015
     */
    public RouteStore selectByPrimaryKey(Long id_route_store) {
        RouteStore key = new RouteStore();
        key.setId_route_store(id_route_store);
        RouteStore record = (RouteStore) getSqlMapClientTemplate().queryForObject("lgk_route_store.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_route_store
     *
     * @abatorgenerated Thu Sep 03 10:12:15 CDT 2015
     */
    public int deleteByExample(RouteStoreExample example) {
        int rows = getSqlMapClientTemplate().delete("lgk_route_store.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_route_store
     *
     * @abatorgenerated Thu Sep 03 10:12:15 CDT 2015
     */
    public int deleteByPrimaryKey(Long id_route_store) {
        RouteStore key = new RouteStore();
        key.setId_route_store(id_route_store);
        int rows = getSqlMapClientTemplate().delete("lgk_route_store.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_route_store
     *
     * @abatorgenerated Thu Sep 03 10:12:15 CDT 2015
     */
    public int countByExample(RouteStoreExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_route_store.abatorgenerated_countByExample", example);
        return count;
    }
}