package com.retailsbs.logistikapp.logistic.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.logistic.dao.UserPositionDAO;
import com.retailsbs.logistikapp.logistic.domain.UserPosition;
import com.retailsbs.logistikapp.logistic.dto.UserPositionExample;

public class UserPositionDAOImpl extends SqlMapClientDaoSupport implements UserPositionDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_position
     *
     * @abatorgenerated Sun Jan 15 14:05:30 CST 2017
     */
    public UserPositionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_position
     *
     * @abatorgenerated Sun Jan 15 14:05:30 CST 2017
     */
    public Long insert(UserPosition record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_user_position.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_position
     *
     * @abatorgenerated Sun Jan 15 14:05:30 CST 2017
     */
    public int updateByPrimaryKey(UserPosition record) {
        int rows = getSqlMapClientTemplate().update("lgk_user_position.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_position
     *
     * @abatorgenerated Sun Jan 15 14:05:30 CST 2017
     */
    public int updateByPrimaryKeySelective(UserPosition record) {
        int rows = getSqlMapClientTemplate().update("lgk_user_position.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_position
     *
     * @abatorgenerated Sun Jan 15 14:05:30 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<UserPosition> selectByExample(UserPositionExample example) {
        List<UserPosition> list = (List<UserPosition>) getSqlMapClientTemplate().queryForList("lgk_user_position.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_position
     *
     * @abatorgenerated Sun Jan 15 14:05:30 CST 2017
     */
    public UserPosition selectByPrimaryKey(Long id_user_position) {
        UserPosition key = new UserPosition();
        key.setId_user_position(id_user_position);
        UserPosition record = (UserPosition) getSqlMapClientTemplate().queryForObject("lgk_user_position.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_position
     *
     * @abatorgenerated Sun Jan 15 14:05:30 CST 2017
     */
    public int deleteByPrimaryKey(Long id_user_position) {
        UserPosition key = new UserPosition();
        key.setId_user_position(id_user_position);
        int rows = getSqlMapClientTemplate().delete("lgk_user_position.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_user_position
     *
     * @abatorgenerated Sun Jan 15 14:05:30 CST 2017
     */
    public int countByExample(UserPositionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_user_position.abatorgenerated_countByExample", example);
        return count;
    }
}