package com.retailsbs.logistikapp.logistic.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.logistic.dao.WayBillDAO;
import com.retailsbs.logistikapp.logistic.domain.WayBill;
import com.retailsbs.logistikapp.logistic.dto.WayBillExample;

public class WayBillDAOImpl extends SqlMapClientDaoSupport implements WayBillDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    public WayBillDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    public Long insert(WayBill record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_waybill.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    public int updateByPrimaryKey(WayBill record) {
        int rows = getSqlMapClientTemplate().update("lgk_waybill.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    public int updateByPrimaryKeySelective(WayBill record) {
        int rows = getSqlMapClientTemplate().update("lgk_waybill.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    @SuppressWarnings("unchecked")
    public List<WayBill> selectByExample(WayBillExample example) {
        List<WayBill> list = (List<WayBill>) getSqlMapClientTemplate().queryForList("lgk_waybill.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    public WayBill selectByPrimaryKey(Long id_waybill) {
        WayBill key = new WayBill();
        key.setId_waybill(id_waybill);
        WayBill record = (WayBill) getSqlMapClientTemplate().queryForObject("lgk_waybill.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    public int deleteByPrimaryKey(Long id_waybill) {
        WayBill key = new WayBill();
        key.setId_waybill(id_waybill);
        int rows = getSqlMapClientTemplate().delete("lgk_waybill.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_waybill
     *
     * @abatorgenerated Thu Apr 07 15:59:52 CDT 2016
     */
    public int countByExample(WayBillExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_waybill.abatorgenerated_countByExample", example);
        return count;
    }
}