package com.retailsbs.logistikapp.commercial.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.retailsbs.logistikapp.commercial.dao.RetailcatGoalDAO;
import com.retailsbs.logistikapp.commercial.domain.RetailcatGoal;
import com.retailsbs.logistikapp.commercial.dto.RetailcatGoalExample;

public class RetailcatGoalDAOImpl extends SqlMapClientDaoSupport implements RetailcatGoalDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retailcat_goal
     *
     * @abatorgenerated Tue Mar 17 08:59:01 CST 2015
     */
    public RetailcatGoalDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retailcat_goal
     *
     * @abatorgenerated Tue Mar 17 08:59:01 CST 2015
     */
    public Long insert(RetailcatGoal record) {
        Object newKey = getSqlMapClientTemplate().insert("lgk_retailcat_goal.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retailcat_goal
     *
     * @abatorgenerated Tue Mar 17 08:59:01 CST 2015
     */
    public int updateByPrimaryKey(RetailcatGoal record) {
        int rows = getSqlMapClientTemplate().update("lgk_retailcat_goal.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retailcat_goal
     *
     * @abatorgenerated Tue Mar 17 08:59:01 CST 2015
     */
    public int updateByPrimaryKeySelective(RetailcatGoal record) {
        int rows = getSqlMapClientTemplate().update("lgk_retailcat_goal.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retailcat_goal
     *
     * @abatorgenerated Tue Mar 17 08:59:01 CST 2015
     */
    @SuppressWarnings("unchecked")
    public List<RetailcatGoal> selectByExample(RetailcatGoalExample example) {
        List<RetailcatGoal> list = (List<RetailcatGoal>) getSqlMapClientTemplate().queryForList("lgk_retailcat_goal.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retailcat_goal
     *
     * @abatorgenerated Tue Mar 17 08:59:01 CST 2015
     */
    public RetailcatGoal selectByPrimaryKey(Long id_retailcat_goal) {
        RetailcatGoal key = new RetailcatGoal();
        key.setId_retailcat_goal(id_retailcat_goal);
        RetailcatGoal record = (RetailcatGoal) getSqlMapClientTemplate().queryForObject("lgk_retailcat_goal.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retailcat_goal
     *
     * @abatorgenerated Tue Mar 17 08:59:01 CST 2015
     */
    public int deleteByPrimaryKey(Long id_retailcat_goal) {
        RetailcatGoal key = new RetailcatGoal();
        key.setId_retailcat_goal(id_retailcat_goal);
        int rows = getSqlMapClientTemplate().delete("lgk_retailcat_goal.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table lgk_retailcat_goal
     *
     * @abatorgenerated Tue Mar 17 08:59:01 CST 2015
     */
    public int countByExample(RetailcatGoalExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("lgk_retailcat_goal.abatorgenerated_countByExample", example);
        return count;
    }
}